import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const overlaySource = readFileSync(fileURLToPath(new URL('../src/components/dramaCanvas/CanvasNodeStatusOverlay.vue', import.meta.url)), 'utf8')
const canvasSource = readFileSync(fileURLToPath(new URL('../src/views/DramaCanvas.vue', import.meta.url)), 'utf8')
const contextMenuSource = readFileSync(fileURLToPath(new URL('../src/components/dramaCanvas/CanvasContextMenu.vue', import.meta.url)), 'utf8')
const storyboardNodeSource = readFileSync(fileURLToPath(new URL('../src/components/dramaCanvas/CanvasStoryboardNode.vue', import.meta.url)), 'utf8')
const mediaNodeSource = readFileSync(fileURLToPath(new URL('../src/components/dramaCanvas/CanvasMediaNode.vue', import.meta.url)), 'utf8')
const assetNodeSource = readFileSync(fileURLToPath(new URL('../src/components/dramaCanvas/CanvasAssetNode.vue', import.meta.url)), 'utf8')
const assetGenerateSource = readFileSync(fileURLToPath(new URL('../src/composables/useCanvasAssetGenerate.js', import.meta.url)), 'utf8')
const scriptNodeSource = readFileSync(fileURLToPath(new URL('../src/components/dramaCanvas/CanvasScriptNode.vue', import.meta.url)), 'utf8')
const scriptActionsSource = readFileSync(fileURLToPath(new URL('../src/composables/useCanvasScript.js', import.meta.url)), 'utf8')

test('节点状态覆盖层提供结果、提示词和失败原因操作', () => {
  assert.match(overlaySource, /打开结果/)
  assert.match(overlaySource, /复制链接/)
  assert.match(overlaySource, /下载结果/)
  assert.match(overlaySource, /存入素材库/)
  assert.match(overlaySource, /复制素材引用/)
  assert.match(overlaySource, /查看素材/)
  assert.match(overlaySource, /failedHint/)
  assert.match(overlaySource, /可点击重试继续执行/)
  assert.match(overlaySource, /queueLabel/)
  assert.match(overlaySource, /步骤 \$\{status\.value\.stepIndex\}\/\$\{status\.value\.stepTotal\}/)
  assert.match(overlaySource, /已恢复中断状态/)
  assert.match(overlaySource, /已恢复运行状态/)
  assert.match(overlaySource, /设为本镜图/)
  assert.match(overlaySource, /设为首帧/)
  assert.match(overlaySource, /设为尾帧/)
  assert.match(overlaySource, /设为本镜视频/)
  assert.match(overlaySource, /设为本镜音频/)
  assert.match(overlaySource, /复制提示词/)
  assert.match(overlaySource, /复制原因/)
  assert.match(overlaySource, /class="result-preview"/)
  assert.match(overlaySource, /<img v-if="resultPreviewType === 'image'"/)
  assert.match(overlaySource, /<video v-else-if="resultPreviewType === 'video'"/)
  assert.match(overlaySource, /<audio v-else-if="resultPreviewType === 'audio'"/)
  assert.match(overlaySource, /function copyPrompt\(\)/)
  assert.match(overlaySource, /function copyResultLink\(\)/)
  assert.match(overlaySource, /function downloadResult\(\)/)
  assert.match(overlaySource, /link\.download = resultFilename\(\)/)
  assert.match(overlaySource, /assetsAPI\.create\(\{/)
  assert.match(overlaySource, /category: 'canvas-result'/)
  assert.match(overlaySource, /source: 'canvas_node_result'/)
  assert.match(overlaySource, /function saveResultAsset\(\)/)
  assert.match(overlaySource, /const effectiveSavedAsset = computed/)
  assert.match(overlaySource, /savedAsset\.value = normalizedAsset/)
  assert.match(overlaySource, /savedAssetId: normalizedAsset\.id/)
  assert.match(overlaySource, /savedAssetName: normalizedAsset\.name/)
  assert.match(overlaySource, /function copyAssetReference\(\)/)
  assert.match(overlaySource, /@素材\(\$\{name\}#\$\{asset\.id\}\)/)
  assert.match(overlaySource, /function viewSavedAsset\(\)/)
  assert.match(overlaySource, /name: 'media-library'/)
  assert.match(overlaySource, /assetId: String\(asset\.id\)/)
  assert.match(overlaySource, /type: resultPreviewType\.value/)
  assert.match(overlaySource, /function attachImageResult\(slot = 'main'\)/)
  assert.match(overlaySource, /imagesAPI\.upload\(\{/)
  assert.match(overlaySource, /frame_type: slot === 'first' \? 'storyboard_first' : slot === 'last' \? 'storyboard_last' : undefined/)
  assert.match(overlaySource, /function attachVideoResult\(\)/)
  assert.match(overlaySource, /videosAPI\.attach\(\{/)
  assert.match(overlaySource, /function attachAudioResult\(\)/)
  assert.match(overlaySource, /storyboardsAPI\.update\(storyboardId, \{ audio_local_path: localPath \}\)/)
  assert.match(overlaySource, /function copyError\(\)/)
})

test('画布节点运行状态会携带当前节点提示词', () => {
  assert.match(canvasSource, /function nodeStepPromptText\(step, sb, node\)/)
  assert.match(canvasSource, /nodeStatus\.set\(nodeId, \{ step, message: statusMessage, promptText/)
  assert.match(canvasSource, /const resultInfo = \{ \.\.\.nodeStepResultInfo\(node, step, sb\.id\), promptText \}/)
  assert.match(canvasSource, /errorDetail: errorMessage/)
})

test('右键节点菜单可直接处理结果和失败重试', () => {
  assert.match(contextMenuSource, /title: '结果'/)
  assert.match(contextMenuSource, /type: 'open-node-result'/)
  assert.match(contextMenuSource, /type: 'copy-node-result'/)
  assert.match(contextMenuSource, /type: 'copy-node-asset-ref'/)
  assert.match(contextMenuSource, /type: 'focus-node-result'/)
  assert.match(contextMenuSource, /type: 'retry-node-failed'/)
  assert.match(canvasSource, /function nodeRuntimeStatus\(node\)/)
  assert.match(canvasSource, /function nodeResultUrl\(node, status = nodeRuntimeStatus\(node\)\)/)
  assert.match(canvasSource, /function resultNodeIdFromStatus\(node, status = nodeRuntimeStatus\(node\)\)/)
  assert.match(canvasSource, /actions\.unshift\('open-node-result', 'copy-node-result'\)/)
  assert.match(canvasSource, /runtimeStatus\?\.savedAssetId/)
  assert.match(canvasSource, /actions\.unshift\('retry-node-failed'\)/)
  assert.match(canvasSource, /function openNodeResult\(node\)/)
  assert.match(canvasSource, /function copyNodeResult\(node\)/)
  assert.match(canvasSource, /function copyNodeAssetReference\(node\)/)
  assert.match(canvasSource, /function focusNodeResult\(node\)/)
  assert.match(canvasSource, /function retryFailedNode\(node\)/)
  assert.match(canvasSource, /if \(type === 'open-node-result'\)/)
  assert.match(canvasSource, /await copyNodeAssetReference\(node\)/)
  assert.match(canvasSource, /await retryFailedNode\(node\)/)
})

test('画布分镜节点回显并复制已指派素材库参考', () => {
  assert.match(canvasSource, /const storyboardAssignedAssets = ref\(\{\}\)/)
  assert.match(canvasSource, /assignedAssets: storyboardAssignedAssets\.value\[storyboardId\] \|\| \[\]/)
  assert.match(canvasSource, /function nodeAssignedAssets\(node\)/)
  assert.match(canvasSource, /function assetReferenceText\(asset\)/)
  assert.match(canvasSource, /function copyNodeAssignedAssetReference\(node\)/)
  assert.match(canvasSource, /actions\.unshift\('copy-node-assigned-asset-ref'\)/)
  assert.match(canvasSource, /await copyNodeAssignedAssetReference\(node\)/)
  assert.match(canvasSource, /storyboardAssignedAssets\.value = assets\.reduce/)
  assert.match(canvasSource, /asset\?\.category === 'canvas-result'/)
  assert.match(contextMenuSource, /type: 'copy-node-assigned-asset-ref'/)
  assert.match(contextMenuSource, /复制指派素材/)
  assert.match(storyboardNodeSource, /const assignedAssets = computed/)
  assert.match(storyboardNodeSource, /class="reference-strip"/)
  assert.match(storyboardNodeSource, /assetThumbUrl\(asset\)/)
  assert.match(storyboardNodeSource, /ctx\?\.setFocusedNode\?\.\(props\.id\)/)
})

test('画布节点生成成功后自动存入素材库并回填素材引用', () => {
  assert.match(canvasSource, /function resultLocalPathFromUrl\(url\)/)
  assert.match(canvasSource, /function nodeResultAssetName\(node, resultInfo\)/)
  assert.match(canvasSource, /async function saveNodeResultAsset\(node, resultInfo, promptText, storyboardId\)/)
  assert.match(canvasSource, /assetsAPI\.create\(\{[\s\S]*category: 'canvas-result'[\s\S]*source: 'canvas_node_result'[\s\S]*auto_saved: true/)
  assert.match(canvasSource, /const savedAssetInfo = await saveNodeResultAsset\(node, resultInfo, promptText, sb\.id\)/)
  assert.match(canvasSource, /const successPayload = \{ \.\.\.resultInfo, \.\.\.\(savedAssetInfo \|\| \{\}\), autoClear: false \}/)
  assert.match(canvasSource, /nodeStatus\.success\(nodeId, successPayload\)/)
  assert.match(canvasSource, /nodeStatus\.success\(sbNodeId, successPayload\)/)
  assert.match(canvasSource, /savedAssetId: asset\.id/)
  assert.match(canvasSource, /savedAssetName: asset\.name \|\| nodeResultAssetName\(node, resultInfo\)/)
})

test('画布节点结果定位和工作流失败状态可恢复重试', () => {
  assert.match(canvasSource, /if \(status\?\.resultNodeId\) return status\.resultNodeId/)
  assert.match(canvasSource, /resultNodeId,/)
  assert.match(canvasSource, /nodeStatus\.set\(`sb:\$\{storyboardId\}`, \{ step, message: label, storyboardId, retryStep: step \}\)/)
  assert.match(canvasSource, /nodeStatus\.fail\(`sb:\$\{storyboardId\}`, \{[\s\S]*retryStep: step[\s\S]*retryLabel: `重试\$\{CANVAS_NODE_STATUS_LABELS\[step\] \|\| step\}`/)
  assert.match(canvasSource, /retryStep: queueNodeRetryStep\(findGraphNode\(`sb:\$\{storyboardId\}`\)\) \|\| 'video'/)
})

test('运行队列区分成功状态并提供结果操作', () => {
  assert.match(canvasSource, /successQueueCount/)
  assert.match(canvasSource, /\{\{ runningQueueCount \}\} 进行中 · \{\{ successQueueCount \}\} 完成 · \{\{ failedQueueCount \}\} 异常/)
  assert.match(canvasSource, /tone: isFailed \? 'failed' : isSuccess \? 'success' : 'running'/)
  assert.match(canvasSource, /function queueSuccessMessage\(status\)/)
  assert.match(canvasSource, /status\.retryStep \|\| queueNodeRetryStep\(findGraphNode\(nodeId\)\)/)
  assert.match(canvasSource, /function openQueueItemResult\(item\)/)
  assert.match(canvasSource, /function copyQueueItemResult\(item\)/)
  assert.match(canvasSource, /function focusQueueItemResult\(item\)/)
  assert.match(canvasSource, /function dismissQueueItem\(item\)/)
  assert.match(canvasSource, /class="run-success-actions"/)
})

test('媒体节点卡片从运行状态恢复结果、失败原因和重试步骤', () => {
  assert.match(mediaNodeSource, /const runtimeStatus = computed\(\(\) => ctx\?\.nodeStatus\?\.map\?\.\[props\.id\] \|\| null\)/)
  assert.match(mediaNodeSource, /runtimeStatus\.value\?\.resultUrl/)
  assert.match(mediaNodeSource, /status\?\.errorDetail \|\| status\?\.detail/)
  assert.match(mediaNodeSource, /failureReason\.value/)
  assert.match(mediaNodeSource, /runtimeStatus\.value\?\.retryStep \|\| props\.data\.kind/)
  assert.match(mediaNodeSource, /<img v-if="resultUrl" :src="resultUrl"/)
  assert.match(mediaNodeSource, /<video v-if="resultUrl" :src="resultUrl"/)
  assert.match(mediaNodeSource, /:generation-error="failureReason"/)
})

test('资产节点卡片显示参考图失败原因并可重试', () => {
  assert.match(assetNodeSource, /import \{ isCanvasNodeBusyStatus \} from '@\/utils\/canvasNodeStatus'/)
  assert.match(assetNodeSource, /const runtimeStatus = computed\(\(\) => ctx\?\.nodeStatus\?\.map\?\.\[props\.id\] \|\| null\)/)
  assert.match(assetNodeSource, /isCanvasNodeBusyStatus\(runtimeStatus\.value\)/)
  assert.match(assetNodeSource, /const failureReason = computed/)
  assert.match(assetNodeSource, /status\?\.errorDetail/)
  assert.match(assetNodeSource, /entity\.generation_error/)
  assert.match(assetNodeSource, /class="asset-error"/)
  assert.match(assetNodeSource, /const retryStep = computed\(\(\) => runtimeStatus\.value\?\.retryStep \|\| 'ref_image'\)/)
  assert.match(assetNodeSource, /function retryAsset\(\)/)
  assert.match(assetNodeSource, /ctx\?\.runNodeStep\?\.\(\{ id: props\.id, type: 'canvasAsset', data: props\.data \}, retryStep\.value\)/)
  assert.match(canvasSource, /if \(node\?\.type === 'canvasAsset'\) \{[\s\S]*await runCanvasAssetNodeStep\(node, step\)/)
  assert.match(canvasSource, /async function runCanvasAssetNodeStep\(node, step\)/)
  assert.match(canvasSource, /await generateAssetReferenceImage\([\s\S]*\{ nodeStatus, drama, refreshDrama, refresh: refreshCanvas \}/)
  assert.match(assetGenerateSource, /retryStep: step/)
  assert.match(assetGenerateSource, /retryLabel: '重试参考图'/)
  assert.match(assetGenerateSource, /nodeStatus\?\.fail\(nodeId, \{/)
  assert.match(assetGenerateSource, /errorDetail: message/)
})

test('脚本节点卡片显示保存和提取失败原因并可按步骤重试', () => {
  assert.match(scriptNodeSource, /import \{ isCanvasNodeBusyStatus \} from '@\/utils\/canvasNodeStatus'/)
  assert.match(scriptNodeSource, /const runtimeStatus = computed\(\(\) => ctx\?\.nodeStatus\?\.map\?\.\[props\.id\] \|\| null\)/)
  assert.match(scriptNodeSource, /isCanvasNodeBusyStatus\(runtimeStatus\.value\)/)
  assert.match(scriptNodeSource, /const failureReason = computed/)
  assert.match(scriptNodeSource, /status\?\.errorDetail/)
  assert.match(scriptNodeSource, /class="script-error"/)
  assert.match(scriptNodeSource, /const retryStep = computed\(\(\) => runtimeStatus\.value\?\.retryStep \|\| ''\)/)
  assert.match(scriptNodeSource, /function retryScript\(\)/)
  assert.match(scriptNodeSource, /retryStep\.value === 'save_script'/)
  assert.match(scriptNodeSource, /api\?\.saveScript\?\.\(episodeId, \{ scriptContent, title \}\)/)
  assert.match(scriptNodeSource, /retryStep\.value === 'extract_chars'/)
  assert.match(scriptNodeSource, /api\?\.extractCharacters\?\.\(episodeId, scriptContent\)/)
  assert.match(scriptNodeSource, /retryStep\.value === 'extract_scenes'/)
  assert.match(scriptNodeSource, /retryStep\.value === 'extract_props'/)
  assert.match(scriptNodeSource, /retryStep\.value === 'extract_all'/)
  assert.match(scriptActionsSource, /function failScriptStatus\(episodeId, step, error\)/)
  assert.match(scriptActionsSource, /nodeStatus\?\.fail\(scriptNodeId\(episodeId\), \{/)
  assert.match(scriptActionsSource, /retryStep: step/)
  assert.match(scriptActionsSource, /function successScriptStatus\(episodeId, step, message\)/)
  assert.match(scriptActionsSource, /nodeStatus\?\.success\(scriptNodeId\(episodeId\), \{/)
  assert.match(scriptActionsSource, /keepOrClearScriptStatus\(episodeId\)/)
})
