import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const canvasSource = readFileSync(fileURLToPath(new URL('../src/views/DramaCanvas.vue', import.meta.url)), 'utf8')
const toolbarSource = readFileSync(fileURLToPath(new URL('../src/components/dramaCanvas/CanvasFloatingToolbar.vue', import.meta.url)), 'utf8')
const contextMenuSource = readFileSync(fileURLToPath(new URL('../src/components/dramaCanvas/CanvasContextMenu.vue', import.meta.url)), 'utf8')
const adapterSource = readFileSync(fileURLToPath(new URL('../src/utils/dramaCanvasAdapter.js', import.meta.url)), 'utf8')

test('画布保留 LibTV 式导航、框选和拖拽历史入口', () => {
  assert.match(canvasSource, /pan-activation-key-code="Space"/)
  assert.match(canvasSource, /zoom-activation-key-code="Control"/)
  assert.match(canvasSource, /:zoom-on-scroll="false"/)
  assert.match(canvasSource, /:pan-on-drag="spacePanning"/)
  assert.match(canvasSource, /function onCanvasKeyup\(event\)/)
  assert.match(canvasSource, /window\.addEventListener\('keyup', onCanvasKeyup\)/)
  assert.match(canvasSource, /window\.removeEventListener\('keyup', onCanvasKeyup\)/)
  assert.match(canvasSource, /:select-nodes-on-drag="true"/)
  assert.match(canvasSource, /selection-mode="partial"/)
  assert.match(canvasSource, /@node-drag-start="onNodeDragStart"/)
  assert.match(canvasSource, /function onCanvasWheel\(event\)/)
  assert.match(canvasSource, /function onCanvasKeydown\(event\)/)
  assert.match(canvasSource, /'Ctrl\/⌘ \+ G：将已选分镜创建为工作流'/)
  assert.match(canvasSource, /'Esc：清空选择、焦点和右键菜单'/)
})

test('悬浮工具栏暴露撤销和重做操作', () => {
  assert.match(toolbarSource, /aria-label="撤销"/)
  assert.match(toolbarSource, /aria-label="重做"/)
  assert.match(toolbarSource, /:disabled="!canUndo"/)
  assert.match(toolbarSource, /:disabled="!canRedo"/)
  assert.match(toolbarSource, /function undo\(\) \{ ctx\?\.undoCanvas\?\.\(\) \}/)
  assert.match(toolbarSource, /function redo\(\) \{ ctx\?\.redoCanvas\?\.\(\) \}/)
})

test('画布工作流支持直接运行所选分镜', () => {
  assert.match(canvasSource, />\s*运行所选\s*</)
  assert.match(canvasSource, /@click="onRunSelectedStoryboards"/)
  assert.match(canvasSource, /async function onRunSelectedStoryboards\(\)/)
  assert.match(canvasSource, /title: '所选分镜'/)
  assert.match(canvasSource, /async function runWorkflowWithConfirm\(runGroup, confirmTitle\)/)
  assert.match(canvasSource, /await runWorkflowWithConfirm\(\{\s*\.\.\.group,/)
})

test('画布支持 LibTV 式键盘完成选择清理和工作流分组', () => {
  assert.match(canvasSource, /function clearCanvasInteractionState\(\)/)
  assert.match(canvasSource, /closeContextMenu\(\)\s*\n\s*focusedNodeId\.value = null\s*\n\s*activeGroupId\.value = null\s*\n\s*applySelectedStoryboardIds\(\[\]\)/)
  assert.match(canvasSource, /if \(key === 'escape' \|\| key === 'esc'\) \{\s*\n\s*event\.preventDefault\(\)\s*\n\s*clearCanvasInteractionState\(\)/)
  assert.match(canvasSource, /if \(key === 'g'\) \{\s*\n\s*event\.preventDefault\(\)\s*\n\s*void onCreateWorkflowGroup\(\)/)
  assert.match(canvasSource, /if \(workflowRunning\.value \|\| layoutSaveState\.value === 'saving'\)/)
})

test('右键空白画布提供 LibTV 式添加节点入口并使用点击位置', () => {
  assert.match(contextMenuSource, /'添加画布节点'/)
  assert.match(contextMenuSource, /<div class="ctx-title">添加节点<\/div>/)
  assert.match(contextMenuSource, /label: '故事脚本'/)
  assert.match(contextMenuSource, /label: '分镜'/)
  assert.match(contextMenuSource, /label: '角色'/)
  assert.match(contextMenuSource, /label: '场景'/)
  assert.match(contextMenuSource, /label: '道具'/)
  assert.match(contextMenuSource, /label: '素材库'/)
  assert.match(contextMenuSource, /label: '上传'/)
  assert.match(contextMenuSource, /label: '粘贴'/)
  assert.match(canvasSource, /contextMenuFlowPos\.value = flowPos/)
  assert.match(canvasSource, /pendingFlowPosition\.value = flowPosition/)
  assert.match(canvasSource, /openCreateDialog\(type, flowPosition\)/)
})

test('右键素材库在画布内弹窗选用并定位项目素材节点', () => {
  assert.match(canvasSource, /import AssetPickerDialog from '@\/components\/AssetPickerDialog\.vue'/)
  assert.match(canvasSource, /import \{ videosAPI \} from '@\/api\/videos'/)
  assert.match(canvasSource, /v-model="canvasAssetPickerVisible"/)
  assert.match(canvasSource, /type="all"/)
  assert.match(canvasSource, /title="从素材库加入画布"/)
  assert.match(canvasSource, /function openCanvasAssetLibrary\(flowPosition = null\)/)
  assert.match(canvasSource, /canvasAssetPickerFlowPos\.value = flowPosition/)
  assert.match(canvasSource, /openCanvasAssetLibrary\(flowPosition\)/)
  assert.doesNotMatch(canvasSource, /router\.push\(\{ name: 'media-library' \}\)/)
  assert.match(canvasSource, /function normalizePickedAssetType\(asset\)/)
  assert.match(canvasSource, /async function ensureProjectMediaAsset\(asset\)/)
  assert.match(canvasSource, /type: normalizePickedAssetType\(asset\)/)
  assert.match(canvasSource, /mediaTypeFromUrl\(url, 'image'\)/)
  assert.match(canvasSource, /function selectedStoryboardMediaAssetPayload\(asset\)/)
  assert.match(canvasSource, /asset\?\.file_url/)
  assert.match(canvasSource, /asset\?\.cover_url/)
  assert.match(canvasSource, /asset\?\.poster_url/)
  assert.match(canvasSource, /asset\?\.file_path/)
  assert.match(canvasSource, /asset\?\.thumbnail_local_path/)
  assert.match(canvasSource, /category: 'canvas-library-pick'/)
  assert.match(canvasSource, /source: 'canvas_asset_picker'/)
  assert.match(canvasSource, /async function placeProjectAssetNode\(asset, flowPosition = null\)/)
  assert.match(canvasSource, /\[nodeId\]: \{ x: flowPosition\.x, y: flowPosition\.y \}/)
  assert.match(canvasSource, /await persistCanvasState\(\{ layoutOnly: true \}\)/)
  assert.match(canvasSource, /async function onCanvasAssetLibraryPick\(asset\)/)
  assert.match(canvasSource, /projectAsset = await ensureProjectMediaAsset\(asset\)/)
  assert.match(canvasSource, /await assignProjectAssetToSelectedStoryboard\(projectAsset\)/)
  assert.match(canvasSource, /if \(mediaPayload\?\.type === 'video'\) \{[\s\S]*await videosAPI\.attach\(\{[\s\S]*storyboard_id: storyboardId,[\s\S]*video_url: mediaPayload\.url,[\s\S]*local_path: mediaPayload\.localPath \|\| undefined/)
  assert.match(canvasSource, /else if \(mediaPayload\?\.type === 'audio'\) \{[\s\S]*await storyboardsAPI\.update\(storyboardId, \{[\s\S]*audio_local_path: mediaPayload\.localPath \|\| undefined,[\s\S]*audio_url: mediaPayload\.localPath \? undefined : mediaPayload\.url/)
  assert.match(canvasSource, /nodeStatus\.success\(nodeId, \{[\s\S]*已从素材库加入画布[\s\S]*savedAssetId: projectAssetId\(projectAsset\)[\s\S]*retryStep: 'library'/)
  assert.match(canvasSource, /nodeStatus\.fail\(nodeId, \{[\s\S]*素材库素材加入画布失败[\s\S]*retryLabel: '重试指派素材'/)
})

test('右键画布支持上传和粘贴素材并按点击位置落点', () => {
  assert.match(canvasSource, /ref="canvasUploadInput"/)
  assert.match(canvasSource, /accept="image\/\*,video\/\*,audio\/\*"/)
  assert.match(canvasSource, /@change="onCanvasUpload"/)
  assert.match(canvasSource, /function openCanvasUpload\(flowPosition = null\)/)
  assert.match(canvasSource, /canvasUploadFlowPos\.value = flowPosition/)
  assert.match(canvasSource, /canvasUploadInput\.value\?\.click\(\)/)
  assert.match(canvasSource, /async function createCanvasProjectAssetFromUpload\(file, flowPosition = null, offsetIndex = 0\)/)
  assert.match(canvasSource, /await uploadAPI\.uploadMedia\(file, \{ dramaId: drama\.value\.id \}\)/)
  assert.match(canvasSource, /category: 'canvas-upload'/)
  assert.match(canvasSource, /source: 'canvas_context_upload'/)
  assert.match(canvasSource, /const targetPos = flowPosition \? \{ x: flowPosition\.x \+ offsetIndex \* 36, y: flowPosition\.y \+ offsetIndex \* 36 \} : null/)
  assert.match(canvasSource, /await placeProjectAssetNode\(asset, targetPos\)/)
  assert.match(canvasSource, /async function pasteCanvasClipboard\(flowPosition = null\)/)
  assert.match(canvasSource, /navigator\.clipboard\?\.read/)
  assert.match(canvasSource, /new File\(\[blob\], `clipboard\.\$\{type\.split\('\/'\)\[1\] \|\| 'bin'\}`/)
  assert.match(canvasSource, /async function createCanvasProjectAssetFromUrl\(url, flowPosition = null\)/)
  assert.match(canvasSource, /category: 'canvas-paste'/)
  assert.match(canvasSource, /source: 'canvas_context_paste'/)
  assert.match(canvasSource, /if \(type === 'upload-media'\) \{[\s\S]*openCanvasUpload\(flowPosition\)/)
  assert.match(canvasSource, /if \(type === 'paste-media'\) \{[\s\S]*await pasteCanvasClipboard\(flowPosition\)/)
})

test('项目图片素材缺少 type 时仍可进入画布素材节点', () => {
  assert.match(adapterSource, /function isProjectMediaAsset\(asset\)/)
  assert.match(adapterSource, /\['image', 'video', 'audio'\]\.includes\(asset\?\.type\) \|\| Boolean\(assetMediaUrl\(asset\)\)/)
  assert.match(adapterSource, /filter\(isProjectMediaAsset\)/)
  assert.match(adapterSource, /项目素材 \$\{projectAssets\.length\}/)
})

test('画布支持手动节点连线并持久化到布局', () => {
  assert.match(canvasSource, /:nodes-connectable="true"/)
  assert.match(canvasSource, /@connect="onConnect"/)
  assert.match(canvasSource, /@edges-change="onEdgesChange"/)
  assert.match(canvasSource, /function manualEdgeId\(connection\)/)
  assert.match(canvasSource, /function hasSameEdgeConnection\(candidate, edgeList = allGraphEdges\.value\)/)
  assert.match(canvasSource, /function onConnect\(connection\)/)
  assert.match(canvasSource, /function onEdgesChange\(changes = \[\]\)/)
  assert.match(canvasSource, /data: \{ manual: true \}/)
  assert.match(canvasSource, /String\(change\.id \|\| ''\)\.startsWith\('manual:'\)/)
  assert.match(canvasSource, /allGraphEdges\.value = stampEdgeBaseStyles\(\[\.\.\.allGraphEdges\.value, edge\]\)/)
  assert.match(canvasSource, /allGraphEdges\.value = allGraphEdges\.value\.filter\(\(edge\) => !removed\.has\(String\(edge\.id\)\)\)/)
  assert.match(canvasSource, /scheduleLayoutSave\(\)/)
  assert.match(canvasSource, /buildCanvasLayoutPayload\(\s*allGraphNodes\.value,\s*currentViewport\.value,\s*layoutCache\.value,\s*allGraphEdges\.value\s*\)/)
})

test('右键节点支持追加下游分镜并自动创建手动连线', () => {
  assert.match(contextMenuSource, /type: 'append-downstream-storyboard'/)
  assert.match(contextMenuSource, /追加下游分镜/)
  assert.match(canvasSource, /actions\.push\('append-downstream-storyboard'\)/)
  assert.match(canvasSource, /node\.type === 'canvasAsset'[\s\S]*'append-downstream-storyboard'[\s\S]*'focus-downstream-video'/)
  assert.match(canvasSource, /async function appendDownstreamStoryboard\(node\)/)
  assert.match(canvasSource, /storyboardForNode\(node\) \|\| \(node\.type === 'canvasAsset' \? firstStoryboardForAssetNode\(node\) : null\)/)
  assert.match(canvasSource, /await storyboardsAPI\.create\(\{/)
  assert.match(canvasSource, /node\.type === 'canvasAsset'[\s\S]*围绕\$\{canvasNodeLabel\(node\)\}设计新分镜/)
  assert.match(canvasSource, /\[targetNodeId\]: targetPosition/)
  assert.match(canvasSource, /id: manualEdgeId\(\{ source: node\.id, target: targetNodeId \}\)/)
  assert.match(canvasSource, /allGraphEdges\.value = stampEdgeBaseStyles\(\[\.\.\.allGraphEdges\.value, edge\]\)/)
  assert.match(canvasSource, /await persistCanvasState\(\{ layoutOnly: true \}\)/)
  assert.match(canvasSource, /await focusCanvasNode\(targetNodeId\)/)
})

test('右键节点支持在现有下游连线中插入分镜并重连', () => {
  assert.match(contextMenuSource, /type: 'insert-downstream-storyboard'/)
  assert.match(contextMenuSource, /插入下游分镜/)
  assert.match(contextMenuSource, /夹到现有连线中/)
  assert.match(canvasSource, /actions\.push\('insert-downstream-storyboard'\)/)
  assert.match(canvasSource, /async function insertDownstreamStoryboard\(node\)/)
  assert.match(canvasSource, /function firstManualDownstreamStoryboardEdge\(node\)/)
  assert.match(canvasSource, /String\(edge\?\.target \|\| ''\)\.startsWith\('sb:'\)/)
  assert.match(canvasSource, /edge\?\.data\?\.manual === true \|\| String\(edge\?\.id \|\| ''\)\.startsWith\('manual:'\)/)
  assert.match(canvasSource, /if \(!downstreamEdge\) \{[\s\S]*await appendDownstreamStoryboard\(node\)/)
  assert.match(canvasSource, /title: `插入分镜 \$\{maxNum \+ 1\}`/)
  assert.match(canvasSource, /const downstreamNode = findGraphNode\(downstreamEdge\.target\)/)
  assert.match(canvasSource, /const firstEdge = \{[\s\S]*source: node\.id,[\s\S]*target: targetNodeId/)
  assert.match(canvasSource, /const secondEdge = \{[\s\S]*source: targetNodeId,[\s\S]*target: downstreamEdge\.target/)
  assert.match(canvasSource, /const remainingEdges = allGraphEdges\.value\.filter\(\(edge\) => String\(edge\.id\) !== String\(downstreamEdge\.id\)\)/)
  assert.match(canvasSource, /const insertedEdges = \[firstEdge, secondEdge\]\.filter\(\(edge\) => !hasSameEdgeConnection\(edge, remainingEdges\)\)/)
  assert.match(canvasSource, /allGraphEdges\.value = stampEdgeBaseStyles\(\[\.\.\.remainingEdges, \.\.\.insertedEdges\]\)/)
  assert.match(canvasSource, /await persistCanvasState\(\{ layoutOnly: true \}\)/)
  assert.match(canvasSource, /await focusCanvasNode\(targetNodeId\)/)
  assert.match(canvasSource, /已插入下游分镜并重连/)
  assert.match(canvasSource, /type === 'insert-downstream-storyboard'[\s\S]*await insertDownstreamStoryboard\(node\)/)
})

test('右键分镜节点可快速选中其所在工作流', () => {
  assert.match(contextMenuSource, /type: 'select-node-workflow'/)
  assert.match(contextMenuSource, /选中所在工作流/)
  assert.match(contextMenuSource, /框选同组分镜/)
  assert.match(canvasSource, /if \(workflowGroupForNode\(node\)\) actions\.push\('select-node-workflow'\)/)
  assert.match(canvasSource, /function workflowGroupForNode\(node\)/)
  assert.match(canvasSource, /\(group\.storyboard_ids \|\| \[\]\)\.map\(Number\)\.includes\(storyboardId\)/)
  assert.match(canvasSource, /function selectWorkflowGroupFromNode\(node\)/)
  assert.match(canvasSource, /selectWorkflowGroup\(group\.id\)/)
  assert.match(canvasSource, /已选中所在工作流/)
  assert.match(canvasSource, /type === 'select-node-workflow'[\s\S]*selectWorkflowGroupFromNode\(node\)/)
})

test('框选多个分镜后右键节点可直接运行所选分镜', () => {
  assert.match(contextMenuSource, /type: 'run-selected-storyboards'/)
  assert.match(contextMenuSource, /运行所选分镜/)
  assert.match(contextMenuSource, /批量生成当前框选/)
  assert.match(canvasSource, /function isSelectedStoryboardNode\(node\)/)
  assert.match(canvasSource, /selectedStoryboardIds\.value\.map\(Number\)\.includes\(storyboardId\)/)
  assert.match(canvasSource, /if \(isSelectedStoryboardNode\(node\) && selectedStoryboardIds\.value\.length > 1\) actions\.push\('run-selected-storyboards'\)/)
  assert.match(canvasSource, /type === 'run-selected-storyboards'[\s\S]*await onRunSelectedStoryboards\(\)/)
})
