import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const canvasSource = readFileSync(fileURLToPath(new URL('../src/views/DramaCanvas.vue', import.meta.url)), 'utf8')
const toolbarSource = readFileSync(fileURLToPath(new URL('../src/components/dramaCanvas/CanvasFloatingToolbar.vue', import.meta.url)), 'utf8')
const contextMenuSource = readFileSync(fileURLToPath(new URL('../src/components/dramaCanvas/CanvasContextMenu.vue', import.meta.url)), 'utf8')
const addButtonSource = readFileSync(fileURLToPath(new URL('../src/components/dramaCanvas/CanvasAddButtonNode.vue', import.meta.url)), 'utf8')
const alignerSource = readFileSync(fileURLToPath(new URL('../src/components/dramaCanvas/CanvasFlowAligner.vue', import.meta.url)), 'utf8')
const adapterSource = readFileSync(fileURLToPath(new URL('../src/utils/dramaCanvasAdapter.js', import.meta.url)), 'utf8')
const workflowOrderPanelSource = readFileSync(fileURLToPath(new URL('../src/components/dramaCanvas/CanvasWorkflowOrderPanel.vue', import.meta.url)), 'utf8')

test('画布保留 LibTV 式导航、框选和拖拽历史入口', () => {
  assert.match(canvasSource, /pan-activation-key-code="Space"/)
  assert.match(canvasSource, /zoom-activation-key-code="Control"/)
  assert.match(canvasSource, /:zoom-on-scroll="false"/)
  assert.match(canvasSource, /:pan-on-drag="spacePanning"/)
  assert.match(canvasSource, /function onCanvasKeyup\(event\)/)
  assert.match(canvasSource, /window\.addEventListener\('keyup', onCanvasKeyup\)/)
  assert.match(canvasSource, /window\.removeEventListener\('keyup', onCanvasKeyup\)/)
  assert.match(canvasSource, /:select-nodes-on-drag="true"/)
  assert.match(canvasSource, /selection-mode="partial"/)
  assert.match(canvasSource, /@node-drag-start="onNodeDragStart"/)
  assert.match(canvasSource, /function onCanvasWheel\(event\)/)
  assert.match(canvasSource, /function syncCanvasViewportFromFlow\(\)/)
  assert.match(canvasSource, /const viewport = canvasFlowApi\.value\?\.getViewport\?\.\(\)/)
  assert.match(canvasSource, /action && typeof action\.finally === 'function'/)
  assert.match(canvasSource, /action\.finally\(syncCanvasViewportFromFlow\)/)
  assert.match(canvasSource, /syncCanvasViewportFromFlow\(\)/)
  assert.match(canvasSource, /function onCanvasKeydown\(event\)/)
  assert.match(canvasSource, /'Ctrl\/⌘ \+ G：将已选分镜创建为工作流'/)
  assert.match(canvasSource, /'Esc：清空选择、焦点和右键菜单'/)
})

test('Space 平移结束后抑制空白点击避免清空当前编辑焦点', () => {
  assert.match(canvasSource, /function setSpacePanning\(active\) \{\s*\n\s*if \(spacePanning\.value === active\) return\s*\n\s*spacePanning\.value = active\s*\n\s*if \(!active\) suppressPaneClick\(\)/)
  assert.match(canvasSource, /function onCanvasKeyup\(event\) \{[\s\S]*setSpacePanning\(false\)/)
  assert.match(canvasSource, /function onCanvasBlur\(\) \{[\s\S]*setSpacePanning\(false\)/)
  assert.match(canvasSource, /function onPaneClick\(event\) \{\s*\n\s*if \(paneClickSuppressed\.value\) return/)
})

test('节点拖拽停止后立即刷新布局缓存并同步视口', () => {
  assert.match(canvasSource, /function refreshLayoutCacheFromGraph\(\) \{[\s\S]*layoutCache\.value = buildCanvasLayoutPayload\([\s\S]*allGraphNodes\.value,[\s\S]*currentViewport\.value,[\s\S]*layoutCache\.value,[\s\S]*allGraphEdges\.value,/)
  assert.match(canvasSource, /function onNodeDragStop\(\) \{\s*\n\s*syncRenderedNodesToGraph\(\)\s*\n\s*syncCanvasViewportFromFlow\(\)\s*\n\s*refreshLayoutCacheFromGraph\(\)/)
  assert.match(canvasSource, /refreshLayoutCacheFromGraph\(\)[\s\S]*if \(dragHistorySnapshot\.value\) commitInteractionHistory\(dragHistorySnapshot\.value\)/)
})

test('悬浮工具栏暴露撤销和重做操作', () => {
  assert.match(toolbarSource, /aria-label="撤销"/)
  assert.match(toolbarSource, /aria-label="重做"/)
  assert.match(toolbarSource, /:disabled="!canUndo"/)
  assert.match(toolbarSource, /:disabled="!canRedo"/)
  assert.match(toolbarSource, /function undo\(\) \{ ctx\?\.undoCanvas\?\.\(\) \}/)
  assert.match(toolbarSource, /function redo\(\) \{ ctx\?\.redoCanvas\?\.\(\) \}/)
})

test('画布工作流支持直接运行所选分镜', () => {
  assert.match(canvasSource, />\s*运行所选\s*</)
  assert.match(canvasSource, /@click="onRunSelectedStoryboards"/)
  assert.match(canvasSource, /async function onRunSelectedStoryboards\(\)/)
  assert.match(canvasSource, /title: '所选分镜'/)
  assert.match(canvasSource, /async function runWorkflowWithConfirm\(runGroup, confirmTitle\)/)
  assert.match(canvasSource, /await runWorkflowWithConfirm\(\{\s*\.\.\.group,/)
})

test('工作流顺序面板点击分镜可回到画布节点', () => {
  assert.match(canvasSource, /@focus="focusWorkflowStoryboard"/)
  assert.match(canvasSource, /async function focusWorkflowStoryboard\(storyboardId\)/)
  assert.match(canvasSource, /applySelectedStoryboardIds\(\[id\]\)/)
  assert.match(canvasSource, /await focusCanvasNode\(`sb:\$\{id\}`\)/)
  assert.match(workflowOrderPanelSource, /const emit = defineEmits\(\['change', 'focus'\]\)/)
  assert.match(workflowOrderPanelSource, /@click="focusItem\(item\)"/)
  assert.match(workflowOrderPanelSource, /@keydown\.enter\.prevent="focusItem\(item\)"/)
  assert.match(workflowOrderPanelSource, /function focusItem\(item\)/)
  assert.match(workflowOrderPanelSource, /emit\('focus', item\.id\)/)
})

test('画布支持 LibTV 式键盘完成选择清理和工作流分组', () => {
  assert.match(canvasSource, /function clearCanvasInteractionState\(\)/)
  assert.match(canvasSource, /closeContextMenu\(\)\s*\n\s*focusedNodeId\.value = null\s*\n\s*activeGroupId\.value = null\s*\n\s*applySelectedStoryboardIds\(\[\]\)/)
  assert.match(canvasSource, /if \(key === 'escape' \|\| key === 'esc'\) \{\s*\n\s*event\.preventDefault\(\)\s*\n\s*clearCanvasInteractionState\(\)/)
  assert.match(canvasSource, /if \(key === 'g'\) \{\s*\n\s*event\.preventDefault\(\)\s*\n\s*void onCreateWorkflowGroup\(\)/)
  assert.match(canvasSource, /if \(workflowRunning\.value \|\| layoutSaveState\.value === 'saving'\)/)
})

test('右键空白画布提供 LibTV 式添加节点入口并使用点击位置', () => {
  assert.match(contextMenuSource, /'添加画布节点'/)
  assert.match(contextMenuSource, /<div class="ctx-title">添加节点<\/div>/)
  assert.match(contextMenuSource, /label: '故事脚本'/)
  assert.match(contextMenuSource, /label: '分镜'/)
  assert.match(contextMenuSource, /label: '角色'/)
  assert.match(contextMenuSource, /label: '场景'/)
  assert.match(contextMenuSource, /label: '道具'/)
  assert.match(contextMenuSource, /label: '图片'/)
  assert.match(contextMenuSource, /label: '视频'/)
  assert.match(contextMenuSource, /label: '音频'/)
  assert.match(contextMenuSource, /type: 'upload-image'/)
  assert.match(contextMenuSource, /type: 'upload-video'/)
  assert.match(contextMenuSource, /type: 'upload-audio'/)
  assert.match(contextMenuSource, /label: '素材库'/)
  assert.match(contextMenuSource, /label: '上传'/)
  assert.match(contextMenuSource, /label: '粘贴'/)
  assert.match(canvasSource, /contextMenuFlowPos\.value = flowPos/)
  assert.match(canvasSource, /pendingFlowPosition\.value = flowPosition/)
  assert.match(canvasSource, /openCreateDialog\(type, flowPosition\)/)
})

test('右键和上传落点优先使用 VueFlow 原生坐标投影', () => {
  assert.match(alignerSource, /const \{ fitView, getViewport, zoomIn, zoomOut, screenToFlowPosition, project \} = useVueFlow\(\)/)
  assert.match(alignerSource, /registerCanvasFlowApi\?\.\(\{ fitView, getViewport, zoomIn, zoomOut, screenToFlowPosition, project \}\)/)
  assert.match(canvasSource, /const api = canvasFlowApi\.value/)
  assert.match(canvasSource, /const viewport = api\?\.getViewport\?\.\(\)/)
  assert.match(canvasSource, /currentViewport\.value = \{ x: viewport\.x, y: viewport\.y, zoom: viewport\.zoom \}/)
  assert.match(canvasSource, /const projectScreenPosition = api\?\.screenToFlowPosition \|\| api\?\.project/)
  assert.match(canvasSource, /const flowPosition = projectScreenPosition\(\{ x: clientX, y: clientY \}\)/)
  assert.match(canvasSource, /Number\.isFinite\(flowPosition\?\.x\) && Number\.isFinite\(flowPosition\?\.y\)/)
})

test('画布加号节点新建内容时沿用加号所在画布落点', () => {
  assert.match(adapterSource, /const addPosition = resolveNodePosition\(savedLayout, addId, \{ x: ASSET_X, y \}\)/)
  assert.match(adapterSource, /data: \{ assetType: sec\.kind, label: '\+ 新建', flowPosition: addPosition \}/)
  assert.match(adapterSource, /const addPosition = resolveNodePosition\(savedLayout, addSbId, \{ x: PIPELINE_X, y: addY \}\)/)
  assert.match(adapterSource, /data: \{ assetType: 'storyboard', label: '\+ 新建分镜', episodeId: episode\.id, flowPosition: addPosition \}/)
  assert.match(addButtonSource, /openCreateDialog\?\.\(props\.data\.assetType, props\.data\.flowPosition \|\| null\)/)
  assert.match(canvasSource, /openCreateDialog\(node\.data\?\.assetType \|\| 'storyboard', node\.data\?\.flowPosition \|\| node\.position \|\| null\)/)
})

test('右键素材库在画布内弹窗选用并定位项目素材节点', () => {
  assert.match(canvasSource, /import AssetPickerDialog from '@\/components\/AssetPickerDialog\.vue'/)
  assert.match(canvasSource, /import \{ videosAPI \} from '@\/api\/videos'/)
  assert.match(canvasSource, /v-model="canvasAssetPickerVisible"/)
  assert.match(canvasSource, /type="all"/)
  assert.match(canvasSource, /title="从素材库加入画布"/)
  assert.match(canvasSource, /function openCanvasAssetLibrary\(flowPosition = null\)/)
  assert.match(canvasSource, /canvasAssetPickerFlowPos\.value = flowPosition/)
  assert.match(canvasSource, /openCanvasAssetLibrary\(flowPosition\)/)
  assert.doesNotMatch(canvasSource, /router\.push\(\{ name: 'media-library' \}\)/)
  assert.match(canvasSource, /function normalizePickedAssetType\(asset\)/)
  assert.match(canvasSource, /async function ensureProjectMediaAsset\(asset\)/)
  assert.match(canvasSource, /type: normalizePickedAssetType\(asset\)/)
  assert.match(canvasSource, /mediaTypeFromUrl\(url, 'image'\)/)
  assert.match(canvasSource, /\['voice', 'tone', 'sound', 'music', 'bgm', 'tts'\]\.includes\(type\)/)
  assert.match(canvasSource, /asset\?\.source_kind === 'voice_catalog'/)
  assert.match(canvasSource, /asset\?\.voice_catalog_id/)
  assert.match(canvasSource, /asset\?\.voice_asset_id/)
  assert.match(canvasSource, /asset\?\.voice_url \|\| asset\?\.voice_local_path/)
  assert.match(canvasSource, /function selectedStoryboardMediaAssetPayload\(asset\)/)
  assert.match(canvasSource, /const type = normalizePickedAssetType\(asset\)/)
  assert.match(canvasSource, /asset\?\.file_url/)
  assert.match(canvasSource, /asset\?\.cover_url/)
  assert.match(canvasSource, /asset\?\.poster_url/)
  assert.match(canvasSource, /asset\?\.file_path/)
  assert.match(canvasSource, /asset\?\.thumbnail_local_path/)
  assert.match(canvasSource, /'canvas-library-pick'/)
  assert.match(canvasSource, /source: 'canvas_asset_picker'/)
  assert.match(canvasSource, /picker_status: asset\?\.picker_status \|\| ''/)
  assert.match(canvasSource, /picker_storyboard_id: asset\?\.picker_storyboard_id \|\| null/)
  assert.match(canvasSource, /voice_catalog_id: asset\?\.voice_catalog_id \|\| asset\?\.voice_catalog\?\.id \|\| asset\?\.voice_catalog\?\.voice_id \|\| null/)
  assert.match(canvasSource, /voice_asset_id: asset\?\.voice_asset_id \|\| asset\?\.voice_catalog\?\.asset_id \|\| null/)
  assert.match(canvasSource, /category: asset\?\.category \|\| \(asset\?\.voice_catalog \|\| asset\?\.voice_catalog_id \|\| asset\?\.voice_asset_id \? 'voice' : 'canvas-library-pick'\)/)
  assert.match(canvasSource, /voice_catalog: asset\?\.voice_catalog \|\| null/)
  assert.match(canvasSource, /async function placeProjectAssetNode\(asset, flowPosition = null\)/)
  assert.match(canvasSource, /\[nodeId\]: \{ x: flowPosition\.x, y: flowPosition\.y \}/)
  assert.match(canvasSource, /await persistCanvasState\(\{ layoutOnly: true \}\)/)
  assert.match(canvasSource, /async function onCanvasAssetLibraryPick\(asset\)/)
  assert.match(canvasSource, /projectAsset = await ensureProjectMediaAsset\(asset\)/)
  assert.match(canvasSource, /function canvasAssetStatusPayload\(asset, overrides = \{\}\)/)
  assert.match(canvasSource, /savedAssetLocalPath: localPath/)
  assert.match(canvasSource, /libraryAsset: asset \|\| null/)
  assert.match(canvasSource, /const pickerSource = asset\?\.picker_source \|\| metadata\.picker_source \|\| asset\?\.source_kind \|\| 'project'/)
  assert.match(canvasSource, /const pickerStatus = asset\?\.picker_status \|\| metadata\.picker_status \|\| ''/)
  assert.match(canvasSource, /const pickerStoryboardId = Number\(asset\?\.picker_storyboard_id \|\| metadata\.picker_storyboard_id \|\| metadata\.attached_storyboard_id \|\| asset\?\.storyboard_id \|\| 0\) \|\| null/)
  assert.match(canvasSource, /const voiceCatalogId = asset\?\.voice_catalog_id \|\| metadata\.voice_catalog_id \|\| asset\?\.voice_catalog\?\.id \|\| asset\?\.voice_catalog\?\.voice_id \|\| null/)
  assert.match(canvasSource, /const voiceAssetId = asset\?\.voice_asset_id \|\| metadata\.voice_asset_id \|\| asset\?\.voice_catalog\?\.asset_id \|\| null/)
  assert.match(canvasSource, /function canvasAssetAttachStatusPayload\(asset, storyboardId, overrides = \{\}\)/)
  assert.match(canvasSource, /storyboardId: storyboardId \|\| undefined/)
  assert.match(canvasSource, /dramaId: drama\.value\?\.id \|\| undefined/)
  assert.match(canvasSource, /function canvasAssetAttachFailurePayload\(asset, storyboardId, overrides = \{\}\)/)
  assert.match(canvasSource, /retryAction: storyboardId \? assetAttachRetryAction\(asset\) : ''/)
  assert.match(canvasSource, /retryActionLabel: storyboardId \? assetAttachRetryLabel\(asset\) : ''/)
  assert.match(canvasSource, /recoverable: true/)
  assert.match(canvasSource, /function selectedStoryboardIdForAssetAttach\(\)/)
  assert.match(canvasSource, /const canvasAssetPickerTargetStoryboardId = ref\(null\)/)
  assert.match(canvasSource, /canvasAssetPickerTargetStoryboardId\.value = selectedStoryboardIdForAssetAttach\(\)/)
  assert.match(canvasSource, /const targetStoryboardId = canvasAssetPickerTargetStoryboardId\.value \|\| selectedStoryboardIdForAssetAttach\(\)/)
  assert.match(canvasSource, /canvasAssetPickerTargetStoryboardId\.value = null/)
  assert.match(canvasSource, /function assetAttachSlot\(asset\)/)
  assert.match(canvasSource, /return 'attach_library_image'/)
  assert.match(canvasSource, /return '重试挂载素材库图片'/)
  assert.match(canvasSource, /const assignResult = await assignProjectAssetToSelectedStoryboard\(projectAsset, \{ silent: true, returnDetail: true, storyboardId: targetStoryboardId \}\)/)
  assert.match(canvasSource, /if \(!assignResult\?\.ok\) throw new Error\(assignResult\?\.message \|\| '素材未指派，请选中一个分镜后重试'\)/)
  assert.match(canvasSource, /projectAsset = assignResult\.asset \|\| projectAsset/)
  assert.match(canvasSource, /if \(mediaPayload\?\.type === 'video'\) \{[\s\S]*await videosAPI\.attach\(\{[\s\S]*storyboard_id: storyboardId,[\s\S]*video_url: mediaPayload\.url,[\s\S]*local_path: mediaPayload\.localPath \|\| undefined/)
  assert.match(canvasSource, /else if \(mediaPayload\?\.type === 'audio'\) \{[\s\S]*await storyboardsAPI\.update\(storyboardId, \{[\s\S]*audio_local_path: mediaPayload\.localPath \|\| undefined,[\s\S]*audio_url: mediaPayload\.localPath \? undefined : mediaPayload\.url/)
  assert.match(canvasSource, /nodeStatus\.success\(nodeId, \{[\s\S]*canvasAssetAttachStatusPayload\(projectAsset \|\| asset, targetStoryboardId, \{[\s\S]*message: resultMessage/)
  assert.match(canvasSource, /nodeStatus\.fail\(nodeId, \{[\s\S]*canvasAssetAttachFailurePayload\(projectAsset \|\| asset, targetStoryboardId, \{[\s\S]*errorDetail: message/)
  assert.match(canvasSource, /if \(item\?\.retryStep === 'library'\) \{[\s\S]*openCanvasAssetLibraryRetry\(\{[\s\S]*nodeId: item\.nodeId \|\| ''/)
  assert.match(canvasSource, /function openCanvasAssetLibraryRetry\(\{ nodeId = '', asset = null, status = null, flowPosition = null, message = '请在素材库中重新选择素材…' \} = \{\}\)/)
})

test('右键画布支持上传和粘贴素材并按点击位置落点', () => {
  assert.match(canvasSource, /ref="canvasUploadInput"/)
  assert.match(canvasSource, /:accept="canvasUploadAccept"/)
  assert.match(canvasSource, /@change="onCanvasUpload"/)
  assert.match(canvasSource, /const canvasUploadAccept = ref\('image\/\*,video\/\*,audio\/\*'\)/)
  assert.match(canvasSource, /function openCanvasUpload\(flowPosition = null, accept = 'image\/\*,video\/\*,audio\/\*'\)/)
  assert.match(canvasSource, /canvasUploadFlowPos\.value = flowPosition/)
  assert.match(canvasSource, /canvasUploadAccept\.value = accept \|\| 'image\/\*,video\/\*,audio\/\*'/)
  assert.match(canvasSource, /canvasUploadInput\.value\?\.click\(\)/)
  assert.match(canvasSource, /async function createCanvasProjectAssetFromUpload\(file, flowPosition = null, offsetIndex = 0\)/)
  assert.match(canvasSource, /await uploadAPI\.uploadMedia\(file, \{ dramaId: drama\.value\.id \}\)/)
  assert.match(canvasSource, /category: 'canvas-upload'/)
  assert.match(canvasSource, /source: 'canvas_context_upload'/)
  assert.match(canvasSource, /const targetPos = flowPosition \? \{ x: flowPosition\.x \+ offsetIndex \* 36, y: flowPosition\.y \+ offsetIndex \* 36 \} : null/)
  assert.match(canvasSource, /await placeProjectAssetNode\(asset, targetPos\)/)
  assert.match(canvasSource, /async function pasteCanvasClipboard\(flowPosition = null\)/)
  assert.match(canvasSource, /navigator\.clipboard\?\.read/)
  assert.match(canvasSource, /new File\(\[blob\], `clipboard\.\$\{type\.split\('\/'\)\[1\] \|\| 'bin'\}`/)
  assert.match(canvasSource, /async function createCanvasProjectAssetFromUrl\(url, flowPosition = null\)/)
  assert.match(canvasSource, /category: 'canvas-paste'/)
  assert.match(canvasSource, /source: 'canvas_context_paste'/)
  assert.match(canvasSource, /if \(type === 'upload-media'\) \{[\s\S]*openCanvasUpload\(flowPosition\)/)
  assert.match(canvasSource, /if \(type === 'upload-image'\) \{[\s\S]*openCanvasUpload\(flowPosition, 'image\/\*'\)/)
  assert.match(canvasSource, /if \(type === 'upload-video'\) \{[\s\S]*openCanvasUpload\(flowPosition, 'video\/\*'\)/)
  assert.match(canvasSource, /if \(type === 'upload-audio'\) \{[\s\S]*openCanvasUpload\(flowPosition, 'audio\/\*'\)/)
  assert.match(canvasSource, /canvasUploadAccept\.value = 'image\/\*,video\/\*,audio\/\*'/)
  assert.match(canvasSource, /if \(type === 'paste-media'\) \{[\s\S]*await pasteCanvasClipboard\(flowPosition\)/)
})

test('项目图片素材缺少 type 时仍可进入画布素材节点', () => {
  assert.match(adapterSource, /function isProjectMediaAsset\(asset\)/)
  assert.match(adapterSource, /\['image', 'video', 'audio'\]\.includes\(asset\?\.type\) \|\| Boolean\(assetMediaUrl\(asset\)\)/)
  assert.match(adapterSource, /filter\(isProjectMediaAsset\)/)
  assert.match(adapterSource, /项目素材 \$\{projectAssets\.length\}/)
})

test('画布支持手动节点连线并持久化到布局', () => {
  assert.match(canvasSource, /:nodes-connectable="true"/)
  assert.match(canvasSource, /@connect="onConnect"/)
  assert.match(canvasSource, /@edges-change="onEdgesChange"/)
  assert.match(canvasSource, /function manualEdgeId\(connection\)/)
  assert.match(canvasSource, /function hasSameEdgeConnection\(candidate, edgeList = allGraphEdges\.value\)/)
  assert.match(canvasSource, /function onConnect\(connection\)/)
  assert.match(canvasSource, /function onEdgesChange\(changes = \[\]\)/)
  assert.match(canvasSource, /data: \{ manual: true \}/)
  assert.match(canvasSource, /String\(change\.id \|\| ''\)\.startsWith\('manual:'\)/)
  assert.match(canvasSource, /allGraphEdges\.value = stampEdgeBaseStyles\(\[\.\.\.allGraphEdges\.value, edge\]\)/)
  assert.match(canvasSource, /allGraphEdges\.value = allGraphEdges\.value\.filter\(\(edge\) => !removed\.has\(String\(edge\.id\)\)\)/)
  assert.match(canvasSource, /scheduleLayoutSave\(\)/)
  assert.match(canvasSource, /buildCanvasLayoutPayload\(\s*allGraphNodes\.value,\s*currentViewport\.value,\s*layoutCache\.value,\s*allGraphEdges\.value\s*\)/)
})

test('右键节点支持追加下游分镜并自动创建手动连线', () => {
  assert.match(contextMenuSource, /type: 'append-downstream-storyboard'/)
  assert.match(contextMenuSource, /追加下游分镜/)
  assert.match(canvasSource, /actions\.push\('append-downstream-storyboard'\)/)
  assert.match(canvasSource, /node\.type === 'canvasAsset'[\s\S]*'append-downstream-storyboard'[\s\S]*'focus-downstream-video'/)
  assert.match(canvasSource, /async function appendDownstreamStoryboard\(node, options = \{\}\)/)
  assert.match(canvasSource, /storyboardForNode\(node\) \|\| \(node\.type === 'canvasAsset' \? firstStoryboardForAssetNode\(node\) : null\)/)
  assert.match(canvasSource, /await storyboardsAPI\.create\(\{/)
  assert.match(canvasSource, /description: downstreamStoryboardDescription\(node, sourceStoryboard, options\.result\)/)
  assert.match(canvasSource, /node\?\.type === 'canvasAsset'[\s\S]*围绕\$\{canvasNodeLabel\(node\)\}设计新分镜/)
  assert.match(canvasSource, /\[targetNodeId\]: targetPosition/)
  assert.match(canvasSource, /id: manualEdgeId\(\{ source: node\.id, target: targetNodeId \}\)/)
  assert.match(canvasSource, /allGraphEdges\.value = stampEdgeBaseStyles\(\[\.\.\.allGraphEdges\.value, edge\]\)/)
  assert.match(canvasSource, /await persistCanvasState\(\{ layoutOnly: true \}\)/)
  assert.match(canvasSource, /await focusCanvasNode\(targetNodeId\)/)
})

test('右键节点结果可直接作为下游参考', () => {
  assert.match(contextMenuSource, /type: 'use-node-result-downstream-reference'/)
  assert.match(contextMenuSource, /作为下游参考/)
  assert.match(contextMenuSource, /追加承接分镜/)
  assert.match(canvasSource, /actions\.unshift\('use-node-result-downstream-reference'\)/)
  assert.match(canvasSource, /type === 'use-node-result-downstream-reference'[\s\S]*await useNodeResultAsDownstreamReference\(node\)/)
  assert.match(canvasSource, /async function useNodeResultAsDownstreamReference\(node, result = \{\}\)/)
  assert.match(canvasSource, /normalizeNodeResultReferences\(node, result\)/)
})

test('右键节点支持在现有下游连线中插入分镜并重连', () => {
  assert.match(contextMenuSource, /type: 'insert-downstream-storyboard'/)
  assert.match(contextMenuSource, /插入下游分镜/)
  assert.match(contextMenuSource, /夹到现有连线中/)
  assert.match(canvasSource, /actions\.push\('insert-downstream-storyboard'\)/)
  assert.match(canvasSource, /async function insertDownstreamStoryboard\(node\)/)
  assert.match(canvasSource, /function firstManualDownstreamStoryboardEdge\(node\)/)
  assert.match(canvasSource, /String\(edge\?\.target \|\| ''\)\.startsWith\('sb:'\)/)
  assert.match(canvasSource, /edge\?\.data\?\.manual === true \|\| String\(edge\?\.id \|\| ''\)\.startsWith\('manual:'\)/)
  assert.match(canvasSource, /if \(!downstreamEdge\) \{[\s\S]*await appendDownstreamStoryboard\(node\)/)
  assert.match(canvasSource, /title: `插入分镜 \$\{maxNum \+ 1\}`/)
  assert.match(canvasSource, /const downstreamNode = findGraphNode\(downstreamEdge\.target\)/)
  assert.match(canvasSource, /const firstEdge = \{[\s\S]*source: node\.id,[\s\S]*target: targetNodeId/)
  assert.match(canvasSource, /const secondEdge = \{[\s\S]*source: targetNodeId,[\s\S]*target: downstreamEdge\.target/)
  assert.match(canvasSource, /const remainingEdges = allGraphEdges\.value\.filter\(\(edge\) => String\(edge\.id\) !== String\(downstreamEdge\.id\)\)/)
  assert.match(canvasSource, /const insertedEdges = \[firstEdge, secondEdge\]\.filter\(\(edge\) => !hasSameEdgeConnection\(edge, remainingEdges\)\)/)
  assert.match(canvasSource, /allGraphEdges\.value = stampEdgeBaseStyles\(\[\.\.\.remainingEdges, \.\.\.insertedEdges\]\)/)
  assert.match(canvasSource, /await persistCanvasState\(\{ layoutOnly: true \}\)/)
  assert.match(canvasSource, /await focusCanvasNode\(targetNodeId\)/)
  assert.match(canvasSource, /已插入下游分镜并重连/)
  assert.match(canvasSource, /type === 'insert-downstream-storyboard'[\s\S]*await insertDownstreamStoryboard\(node\)/)
})

test('右键分镜节点可快速选中其所在工作流', () => {
  assert.match(contextMenuSource, /type: 'select-node-workflow'/)
  assert.match(contextMenuSource, /选中所在工作流/)
  assert.match(contextMenuSource, /框选同组分镜/)
  assert.match(canvasSource, /if \(workflowGroupForNode\(node\)\) actions\.push\('select-node-workflow', 'remove-node-workflow'\)/)
  assert.match(canvasSource, /function workflowGroupForNode\(node\)/)
  assert.match(canvasSource, /\(group\.storyboard_ids \|\| \[\]\)\.map\(Number\)\.includes\(storyboardId\)/)
  assert.match(canvasSource, /function selectWorkflowGroupFromNode\(node\)/)
  assert.match(canvasSource, /selectWorkflowGroup\(group\.id\)/)
  assert.match(canvasSource, /已选中所在工作流/)
  assert.match(canvasSource, /type === 'select-node-workflow'[\s\S]*selectWorkflowGroupFromNode\(node\)/)
})

test('右键分镜节点可从所在工作流移出', () => {
  assert.match(contextMenuSource, /type: 'remove-node-workflow'/)
  assert.match(contextMenuSource, /移出工作流/)
  assert.match(contextMenuSource, /取消当前分镜分组/)
  assert.match(canvasSource, /import \{[\s\S]*removeStoryboardFromWorkflowGroup,[\s\S]*\} from '@\/utils\/canvasWorkflow'/)
  assert.match(canvasSource, /if \(workflowGroupForNode\(node\)\) actions\.push\('select-node-workflow', 'remove-node-workflow'\)/)
  assert.match(canvasSource, /async function removeNodeFromWorkflowGroup\(node\)/)
  assert.match(canvasSource, /const nextGroups = removeStoryboardFromWorkflowGroup\(workflowGroups\.value, group\.id, storyboardId\)/)
  assert.match(canvasSource, /workflowGroups\.value = previousGroups[\s\S]*activeGroupId\.value = previousActiveGroupId[\s\S]*selectedStoryboardIds\.value = previousSelectedIds/)
  assert.match(canvasSource, /type === 'remove-node-workflow'[\s\S]*await removeNodeFromWorkflowGroup\(node\)/)
})

test('框选多个分镜后右键节点可直接运行所选分镜', () => {
  assert.match(contextMenuSource, /type: 'run-selected-storyboards'/)
  assert.match(contextMenuSource, /运行所选分镜/)
  assert.match(contextMenuSource, /批量生成当前框选/)
  assert.match(canvasSource, /function isSelectedStoryboardNode\(node\)/)
  assert.match(canvasSource, /selectedStoryboardIds\.value\.map\(Number\)\.includes\(storyboardId\)/)
  assert.match(canvasSource, /if \(isSelectedStoryboardNode\(node\) && selectedStoryboardIds\.value\.length > 1\) actions\.push\('run-selected-storyboards'\)/)
  assert.match(canvasSource, /type === 'run-selected-storyboards'[\s\S]*await onRunSelectedStoryboards\(\)/)
})
