import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const canvasSource = readFileSync(fileURLToPath(new URL('../src/views/DramaCanvas.vue', import.meta.url)), 'utf8')
const contextMenuSource = readFileSync(fileURLToPath(new URL('../src/components/dramaCanvas/CanvasContextMenu.vue', import.meta.url)), 'utf8')
const storyboardPanelSource = readFileSync(fileURLToPath(new URL('../src/components/dramaCanvas/CanvasStoryboardPanel.vue', import.meta.url)), 'utf8')
const assetPanelSource = readFileSync(fileURLToPath(new URL('../src/components/dramaCanvas/CanvasAssetPanel.vue', import.meta.url)), 'utf8')
const mediaPanelSource = readFileSync(fileURLToPath(new URL('../src/components/dramaCanvas/CanvasMediaPanel.vue', import.meta.url)), 'utf8')
const dramaCanvasAdapterSource = readFileSync(fileURLToPath(new URL('../src/utils/dramaCanvasAdapter.js', import.meta.url)), 'utf8')
const storyboardNodeSource = readFileSync(fileURLToPath(new URL('../src/components/dramaCanvas/CanvasStoryboardNode.vue', import.meta.url)), 'utf8')
const projectAssetNodeSource = readFileSync(fileURLToPath(new URL('../src/components/dramaCanvas/CanvasProjectAssetNode.vue', import.meta.url)), 'utf8')

test('右键节点菜单保留配置面板入口', () => {
  assert.match(contextMenuSource, /type: 'open-node-config'/)
  assert.match(contextMenuSource, /打开节点配置/)
  assert.match(canvasSource, /if \(type === 'open-node-config'\) \{/)
  assert.match(canvasSource, /openNodeConfig\(node\)/)
  assert.match(canvasSource, /function openNodeConfig\(node\)/)
  assert.match(canvasSource, /PANEL_NODE_TYPES\.has\(node\.type\)[\s\S]*focusedNodeId\.value = node\.id/)
  assert.match(canvasSource, /'canvasProjectAsset'/)
})

test('分镜配置面板保留保存、回显刷新和单镜模型配置', () => {
  assert.match(storyboardPanelSource, /function saveFields\(\)/)
  assert.match(storyboardPanelSource, /await persistForm\(false\)/)
  assert.match(storyboardPanelSource, /await ctx\?\.refreshDrama\?\.\(true\)/)
  assert.match(storyboardPanelSource, /actionStatus\.value = \{ type: 'success', message: '保存完成' \}/)
  assert.match(storyboardPanelSource, />恢复</)
  assert.match(storyboardPanelSource, /function resetFields\(\)/)
  assert.match(storyboardPanelSource, /syncForm\(props\.storyboard\)/)
  assert.match(storyboardPanelSource, /已恢复到上次保存/)
  assert.match(storyboardPanelSource, /CanvasGenerationOptions/)
  assert.match(storyboardPanelSource, /function saveStoryboardGenerationOptions\(patch, next\)/)
})

test('节点配置面板支持完整生成参数而非只改模型', () => {
  assert.doesNotMatch(storyboardPanelSource, /<CanvasGenerationOptions[\s\S]*models-only[\s\S]*@change="saveStoryboardGenerationOptions"[\s\S]*\/>/)
  assert.match(storyboardPanelSource, /label="生成参数"/)
  assert.match(storyboardPanelSource, /画幅与清晰度保存为项目生成参数/)
  assert.match(storyboardPanelSource, /Object\.hasOwn\(patch, 'aspectRatio'\)/)
  assert.match(storyboardPanelSource, /Object\.hasOwn\(patch, 'videoResolution'\)/)
  assert.match(storyboardPanelSource, /ctx\?\.updateGenerationOptions\?\.\(/)
  assert.doesNotMatch(mediaPanelSource, /<CanvasGenerationOptions[\s\S]*models-only[\s\S]*@change="saveStoryboardGenerationOptions"[\s\S]*\/>/)
  assert.match(mediaPanelSource, /label="生成参数"/)
  assert.match(mediaPanelSource, /Object\.hasOwn\(patch, 'aspectRatio'\)/)
  assert.match(mediaPanelSource, /Object\.hasOwn\(patch, 'videoResolution'\)/)
  assert.match(mediaPanelSource, /ctx\?\.updateGenerationOptions\?\.\(/)
})

test('分镜配置面板保留素材库指派、摄影控制、声音策略和连续性入口', () => {
  assert.match(storyboardPanelSource, /从素材库指派参考图/)
  assert.match(storyboardPanelSource, /command="first_frame"/)
  assert.match(storyboardPanelSource, /command="last_frame"/)
  assert.match(storyboardPanelSource, /command="video"/)
  assert.match(storyboardPanelSource, /command="audio"/)
  assert.match(storyboardPanelSource, /:type="assetLibraryType"/)
  assert.match(storyboardPanelSource, /:title="assetLibraryTitle"/)
  assert.match(storyboardPanelSource, /:drama-id="ctx\?\.drama\?\.value\?\.id"/)
  assert.match(storyboardPanelSource, /function onAssetLibraryPick\(asset\)/)
  assert.match(storyboardPanelSource, /assetsAPI\.update\(projectAssetId\(asset\), \{ drama_id: dramaId, storyboard_id: storyboardId \}\)/)
  assert.match(storyboardPanelSource, /assetsAPI\.create\(\{[\s\S]*storyboard_id: storyboardId[\s\S]*category: 'storyboard_reference'/)
  assert.match(storyboardPanelSource, /assetsAPI\.list\(\{ storyboard_id: sbId, page: 1, page_size: 20 \}\)/)
  assert.doesNotMatch(storyboardPanelSource, /assetsAPI\.list\(\{ storyboard_id: sbId, type: 'image'/)
  assert.match(storyboardPanelSource, /type: asset\.type \|\| 'image'/)
  assert.match(storyboardPanelSource, /<video v-if="reference\.type === 'video'"/)
  assert.match(storyboardPanelSource, /v-else-if="reference\.type === 'audio'"/)
  assert.match(storyboardPanelSource, /await loadAssignedAssets\(\)/)
  assert.match(storyboardPanelSource, /normalizeAssignedAsset\(savedAsset\)/)
  assert.match(storyboardPanelSource, /camera-control-strip/)
  assert.match(storyboardPanelSource, /function savePhotography\(\)/)
  assert.match(storyboardPanelSource, /gridFrameType\.value/)
  assert.match(storyboardPanelSource, /视频模型与声音/)
  assert.match(storyboardPanelSource, /buildVoicePromptPreview/)
  assert.match(storyboardPanelSource, /镜头连续性/)
  assert.match(storyboardPanelSource, /function linkTailFrame\(\)/)
  assert.match(storyboardPanelSource, /ctx\?\.nodeStatus\?\.set\(sbNodeId\.value, \{ step: 'link_tail_frame', message: '尾帧衔接中…' \}\)/)
  assert.match(storyboardPanelSource, /ctx\?\.nodeStatus\?\.fail\(sbNodeId\.value, \{[\s\S]*retryStep: 'link_tail_frame'[\s\S]*retryLabel: '重试尾帧衔接'/)
  assert.match(storyboardPanelSource, /errorDetail: errorMessage/)
  assert.match(storyboardPanelSource, /imagesBySbId: ctx\?\.imagesBySbId\?\.value \|\| \{\}/)
  assert.match(storyboardPanelSource, /videosBySbId: ctx\?\.videosBySbId\?\.value \|\| \{\}/)
})

test('分镜配置面板支持素材库按用途挂载到分镜字段', () => {
  assert.match(storyboardPanelSource, /const assetAttachTarget = ref\('reference'\)/)
  assert.match(storyboardPanelSource, /const ASSET_ATTACH_TARGETS = \{/)
  assert.match(storyboardPanelSource, /function openAssetLibrary\(target = 'reference'\)/)
  assert.match(storyboardPanelSource, /assetAttachTarget\.value = ASSET_ATTACH_TARGETS\[target\] \? target : 'reference'/)
  assert.match(storyboardPanelSource, /async function attachPickedAssetToStoryboard\(target, asset\)/)
  assert.match(storyboardPanelSource, /payload\.first_frame_image_id = null/)
  assert.match(storyboardPanelSource, /payload\.image_url = localPath \? null : url/)
  assert.match(storyboardPanelSource, /payload\.local_path = localPath \|\| null/)
  assert.match(storyboardPanelSource, /payload\.last_frame_image_id = null/)
  assert.match(storyboardPanelSource, /payload\.last_frame_image_url = localPath \? null : url/)
  assert.match(storyboardPanelSource, /payload\.last_frame_local_path = localPath \|\| null/)
  assert.match(storyboardPanelSource, /payload\.video_url = url/)
  assert.match(storyboardPanelSource, /payload\.audio_local_path = localPath \|\| undefined/)
  assert.match(storyboardPanelSource, /payload\.audio_url = localPath \? undefined : url/)
  assert.match(storyboardPanelSource, /await storyboardsAPI\.update\(storyboardId, payload\)/)
})

test('资产配置面板保留保存、素材库选图和关联分镜入口', () => {
  assert.match(assetPanelSource, /function saveAsset\(\)/)
  assert.match(assetPanelSource, /await ctx\?\.refreshDrama\?\.\(true\)/)
  assert.match(assetPanelSource, /素材库选图/)
  assert.match(assetPanelSource, /AssetPickerDialog/)
  assert.match(assetPanelSource, /关联分镜/)
  assert.match(assetPanelSource, /function highlightRelated\(\)/)
})

test('资产配置面板从项目素材库选图后写回画布资产绑定', () => {
  assert.match(assetPanelSource, /import \{ assetsAPI \} from '@\/api\/assets'/)
  assert.match(assetPanelSource, /async function bindPickedProjectAsset\(asset\)/)
  assert.match(assetPanelSource, /asset\?\.source_kind !== 'project'/)
  assert.match(assetPanelSource, /assetsAPI\.update\(asset\.raw_id/)
  assert.match(assetPanelSource, /canvas_asset_binding/)
  assert.match(assetPanelSource, /kind: props\.kind/)
  assert.match(assetPanelSource, /entity_id: props\.entity\.id/)
  assert.match(assetPanelSource, /node_id: props\.nodeId/)
  assert.match(assetPanelSource, /await bindPickedProjectAsset\(asset\)/)
})

test('媒体配置面板支持从素材库复用视频和音频', () => {
  assert.match(mediaPanelSource, /从素材库选用成片/)
  assert.match(mediaPanelSource, /from '@\/components\/AssetPickerDialog\.vue'/)
  assert.match(mediaPanelSource, /asset\.asset_url \|\| asset\.display_url \|\| asset\.url/)
  assert.match(mediaPanelSource, /async function onLibraryAudioPick\(asset\)/)
  assert.match(mediaPanelSource, /从素材库选用音频/)
  assert.match(mediaPanelSource, /type="audio"/)
  assert.match(mediaPanelSource, /素材库音频挂载中/)
  assert.match(mediaPanelSource, /storyboardsAPI\.update\(sbId, \{/)
  assert.match(mediaPanelSource, /audio_local_path: localPath \|\| undefined/)
  assert.match(mediaPanelSource, /audio_url: localPath \? undefined : audioUrl/)
  assert.match(mediaPanelSource, /已将素材库音频设为该分镜音频/)
  assert.match(dramaCanvasAdapterSource, /const dialogueAudio = sb\.audio_local_path \|\| sb\.audio_url/)
  assert.match(dramaCanvasAdapterSource, /url: audioUrl\(dialogueAudio\)/)
  assert.match(storyboardNodeSource, /props\.data\.storyboard\?\.audio_url/)
})

test('媒体配置面板失败后保留原因和重试入口', () => {
  assert.match(mediaPanelSource, /v-if="failedStatus"/)
  assert.match(mediaPanelSource, /failedStatus\.errorDetail \|\| failedStatus\.message/)
  assert.match(mediaPanelSource, /@click\.stop="retryFailedStep"/)
  assert.match(mediaPanelSource, /const activeNodeStatus = computed/)
  assert.match(mediaPanelSource, /activeNodeStatus\.value\?\.step === 'failed'/)
  assert.match(mediaPanelSource, /retryStep: step/)
  assert.match(mediaPanelSource, /retryLabel/)
  assert.match(mediaPanelSource, /recoverable: true/)
  assert.match(mediaPanelSource, /async function retryFailedStep\(\)/)
  assert.match(mediaPanelSource, /await runStep\(step\)/)
})

test('媒体配置面板成功后保留节点结果回显', () => {
  assert.match(mediaPanelSource, /function markNodeSuccess\(message, payload = \{\}\)/)
  assert.match(mediaPanelSource, /ctx\?\.nodeStatus\?\.success\(props\.nodeId, status\)/)
  assert.match(mediaPanelSource, /ctx\?\.nodeStatus\?\.success\(sbNodeId\.value, status\)/)
  assert.match(mediaPanelSource, /autoClear: payload\.autoClear \?\? false/)
  assert.match(mediaPanelSource, /resultType: 'video'/)
  assert.match(mediaPanelSource, /resultType: 'audio'/)
  assert.match(mediaPanelSource, /resultType: 'text'/)
  assert.match(mediaPanelSource, /promptText: nextText/)
  assert.match(mediaPanelSource, /promptText: universalText\.value\.trim\(\)/)
  assert.match(mediaPanelSource, /function clearRunningStatus\(nodeId\)/)
  assert.match(mediaPanelSource, /!\['failed', 'success'\]\.includes\(status\.step\)/)
  assert.match(mediaPanelSource, /function currentResultUrl\(step\)/)
})

test('项目素材节点聚焦后提供配置面板和挂载动作', () => {
  assert.match(projectAssetNodeSource, /v-if="data\.focused"/)
  assert.match(projectAssetNodeSource, /素材配置/)
  assert.match(projectAssetNodeSource, /closePanel/)
  assert.match(projectAssetNodeSource, /复制到提示词/)
  assert.match(projectAssetNodeSource, /指派到选中分镜/)
  assert.match(projectAssetNodeSource, /ctx\?\.runNodeStep\?\.\(\{ id: props\.id, type: 'canvasProjectAsset', data: props\.data \}, 'library'\)/)
  assert.match(projectAssetNodeSource, /ctx\?\.clearFocusedNode\?\.\(\)/)
})
