import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const overlaySource = readFileSync(fileURLToPath(new URL('../src/components/dramaCanvas/CanvasNodeStatusOverlay.vue', import.meta.url)), 'utf8')
const canvasSource = readFileSync(fileURLToPath(new URL('../src/views/DramaCanvas.vue', import.meta.url)), 'utf8')
const contextMenuSource = readFileSync(fileURLToPath(new URL('../src/components/dramaCanvas/CanvasContextMenu.vue', import.meta.url)), 'utf8')
const storyboardNodeSource = readFileSync(fileURLToPath(new URL('../src/components/dramaCanvas/CanvasStoryboardNode.vue', import.meta.url)), 'utf8')
const mediaNodeSource = readFileSync(fileURLToPath(new URL('../src/components/dramaCanvas/CanvasMediaNode.vue', import.meta.url)), 'utf8')
const assetNodeSource = readFileSync(fileURLToPath(new URL('../src/components/dramaCanvas/CanvasAssetNode.vue', import.meta.url)), 'utf8')
const assetGenerateSource = readFileSync(fileURLToPath(new URL('../src/composables/useCanvasAssetGenerate.js', import.meta.url)), 'utf8')
const scriptNodeSource = readFileSync(fileURLToPath(new URL('../src/components/dramaCanvas/CanvasScriptNode.vue', import.meta.url)), 'utf8')
const scriptActionsSource = readFileSync(fileURLToPath(new URL('../src/composables/useCanvasScript.js', import.meta.url)), 'utf8')
const projectAssetNodeSource = readFileSync(fileURLToPath(new URL('../src/components/dramaCanvas/CanvasProjectAssetNode.vue', import.meta.url)), 'utf8')

test('节点状态覆盖层提供结果、提示词和失败原因操作', () => {
  assert.match(overlaySource, /打开结果/)
  assert.match(overlaySource, /复制链接/)
  assert.match(overlaySource, /下载结果/)
  assert.match(overlaySource, /存入素材库/)
  assert.match(overlaySource, /复制素材引用/)
  assert.match(overlaySource, /查看素材/)
  assert.match(overlaySource, /failedHint/)
  assert.match(overlaySource, /可点击重试继续执行/)
  assert.match(overlaySource, /queueLabel/)
  assert.match(overlaySource, /步骤 \$\{status\.value\.stepIndex\}\/\$\{status\.value\.stepTotal\}/)
  assert.match(overlaySource, /已恢复中断状态/)
  assert.match(overlaySource, /已恢复运行状态/)
  assert.match(overlaySource, /设为本镜图/)
  assert.match(overlaySource, /设为首帧/)
  assert.match(overlaySource, /设为尾帧/)
  assert.match(overlaySource, /设为本镜视频/)
  assert.match(overlaySource, /设为本镜音频/)
  assert.match(overlaySource, /复制提示词/)
  assert.match(overlaySource, /复制上游引用/)
  assert.match(overlaySource, /class="action-error"/)
  assert.match(overlaySource, /class="action-group action-group-primary"/)
  assert.match(overlaySource, /class="action-group action-group-asset"/)
  assert.match(overlaySource, /class="action-group action-group-attach"/)
  assert.match(overlaySource, /class="action-group action-group-flow"/)
  assert.match(overlaySource, /flex-wrap: wrap/)
  assert.match(overlaySource, /max-width: calc\(100% - 14px\)/)
  assert.match(overlaySource, /\.action-group \{/)
  assert.match(overlaySource, /const actionErrorText = computed/)
  assert.match(overlaySource, /status\.retryActionLabel \|\| '重试操作'/)
  assert.match(overlaySource, /v-if="status\.retryAction" type="button" :disabled="savingAsset \|\| attachingResult" @click\.stop="retryAction"/)
  assert.match(overlaySource, /function markActionFailure\(message, retryActionName, retryActionLabel\)/)
  assert.match(overlaySource, /actionError: text/)
  assert.match(overlaySource, /retryAction: retryActionName/)
  assert.match(overlaySource, /function retryAction\(\)/)
  assert.match(overlaySource, /action === 'save_result_asset'/)
  assert.match(overlaySource, /action === 'attach_image_first'/)
  assert.match(overlaySource, /action === 'attach_image_last'/)
  assert.match(overlaySource, /action === 'attach_library_image'/)
  assert.match(overlaySource, /attachImageResult\(libraryImageRetrySlot\(\)\)/)
  assert.match(overlaySource, /function libraryImageRetrySlot\(\)/)
  assert.match(overlaySource, /\['first', 'last', 'main'\]\.includes\(slot\) \? slot : 'main'/)
  assert.match(overlaySource, /action === 'attach_video'/)
  assert.match(overlaySource, /action === 'attach_library_video'/)
  assert.match(overlaySource, /action === 'attach_audio'/)
  assert.match(overlaySource, /action === 'attach_library_audio'/)
  assert.match(overlaySource, /复制原因/)
  assert.match(overlaySource, /已引用 \$\{upstreamReferenceUrls\.value\.length\} 个上游结果/)
  assert.match(overlaySource, /const effectiveResultUrl = computed\(\(\) => effectiveSavedAsset\.value\?\.url \|\| status\.value\?\.resultUrl \|\| ''\)/)
  assert.match(overlaySource, /const hasResultPreview = computed\(\(\) => Boolean\(effectiveResultUrl\.value\) && \(isSuccess\.value \|\| isFailed\.value\)\)/)
  assert.match(overlaySource, /v-if="hasResultPreview"/)
  assert.match(overlaySource, /class="result-preview"/)
  assert.match(overlaySource, /<img v-if="resultPreviewType === 'image'" :src="effectiveResultUrl"/)
  assert.match(overlaySource, /<video v-else-if="resultPreviewType === 'video'" :src="effectiveResultUrl"/)
  assert.match(overlaySource, /<audio v-else-if="resultPreviewType === 'audio'" :src="effectiveResultUrl"/)
  assert.match(overlaySource, /<span v-if="effectiveResultUrl" class="action-group action-group-primary"/)
  assert.match(overlaySource, /<span v-if="isFailed" class="failed-actions">[\s\S]*打开结果[\s\S]*复制链接[\s\S]*下载结果/)
  assert.match(overlaySource, /function copyPrompt\(\)/)
  assert.match(overlaySource, /function copyResultLink\(\)/)
  assert.match(overlaySource, /function copyUpstreamReferences\(\)/)
  assert.match(overlaySource, /const upstreamReferenceUrls = computed/)
  assert.match(overlaySource, /function downloadResult\(\)/)
  assert.match(overlaySource, /link\.download = resultFilename\(\)/)
  assert.match(overlaySource, /window\.open\(effectiveResultUrl\.value/)
  assert.match(overlaySource, /copyText\(effectiveResultUrl\.value/)
  assert.match(overlaySource, /link\.href = effectiveResultUrl\.value/)
  assert.match(overlaySource, /assetsAPI\.create\(\{/)
  assert.match(overlaySource, /category: 'canvas-result'/)
  assert.match(overlaySource, /source: 'canvas_node_result'/)
  assert.match(overlaySource, /function saveResultAsset\(\)/)
  assert.match(overlaySource, /const effectiveSavedAsset = computed/)
  assert.match(overlaySource, /savedAsset\.value = normalizedAsset/)
  assert.match(overlaySource, /savedAssetId: normalizedAsset\.id/)
  assert.match(overlaySource, /savedAssetName: normalizedAsset\.name/)
  assert.match(overlaySource, /markActionFailure\(message, 'save_result_asset', '重试存入素材库'\)/)
  assert.match(overlaySource, /function copyAssetReference\(\)/)
  assert.match(overlaySource, /@素材\(\$\{name\}#\$\{asset\.id\}\)/)
  assert.match(overlaySource, /function viewSavedAsset\(\)/)
  assert.match(overlaySource, /name: 'media-library'/)
  assert.match(overlaySource, /assetId: String\(asset\.id\)/)
  assert.match(overlaySource, /type: resultPreviewType\.value/)
  assert.match(overlaySource, /function attachImageResult\(slot = 'main'\)/)
  assert.match(overlaySource, /imagesAPI\.upload\(\{/)
  assert.match(overlaySource, /frame_type: slot === 'first' \? 'storyboard_first' : slot === 'last' \? 'storyboard_last' : undefined/)
  assert.match(overlaySource, /markActionFailure\(message, `attach_image_\$\{slot\}`/)
  assert.match(overlaySource, /function attachVideoResult\(\)/)
  assert.match(overlaySource, /videosAPI\.attach\(\{/)
  assert.match(overlaySource, /markActionFailure\(message, 'attach_video', '重试设为本镜视频'\)/)
  assert.match(overlaySource, /function attachAudioResult\(\)/)
  assert.match(overlaySource, /const canAttachAudio = computed\(\(\) => isSuccess\.value && resultPreviewType\.value === 'audio' && Boolean\(resultUrl\(\)\)/)
  assert.match(overlaySource, /audio_url: localPath \? undefined : audioUrl/)
  assert.match(overlaySource, /markActionFailure\(message, 'attach_audio', '重试设为本镜音频'\)/)
  assert.match(overlaySource, /function markAttachSuccess\(message, extra = \{\}\)/)
  assert.match(overlaySource, /attachedToStoryboardId: resultStoryboardId\(runtimeNode\(\)\)/)
  assert.match(overlaySource, /markAttachSuccess\('已设为本镜音频'/)
  assert.match(overlaySource, /function copyError\(\)/)
})

test('画布节点运行状态会携带当前节点提示词', () => {
  assert.match(canvasSource, /function nodeStepPromptText\(step, sb, node\)/)
  assert.match(canvasSource, /function nodeStepStatusIds\(node, step, storyboardId\)/)
  assert.match(canvasSource, /nodeStepResultInfo\(node, step, storyboardId\)\.resultNodeId/)
  assert.match(canvasSource, /function setNodeStepStatus\(statusIds, payload\)/)
  assert.match(canvasSource, /statusIds\.forEach\(\(id\) => nodeStatus\.set\(id, payload\)\)/)
  assert.match(canvasSource, /const statusIds = nodeStepStatusIds\(node, step, sb\.id\)/)
  assert.match(canvasSource, /const runKey = `storyboard:\$\{sb\.id\}:\$\{step\}:\$\{Date\.now\(\)\}`/)
  assert.match(canvasSource, /function nodeStepTaskStatusOptions\(statusIds, basePayload\)/)
  assert.match(canvasSource, /onTask\(task\) \{[\s\S]*taskId: task\?\.taskId \|\| ''[\s\S]*任务已创建/)
  assert.match(canvasSource, /onPoll\(task\) \{[\s\S]*progress: task\?\.progress \?\? null/)
  assert.match(canvasSource, /const taskStatusOptions = nodeStepTaskStatusOptions\(statusIds, \{ \.\.\.baseStatusPayload, promptText \}\)/)
  assert.match(canvasSource, /const upstreamReferenceUrlsForNode = nodeInputReferenceUrls\(node\)/)
  assert.match(canvasSource, /const baseStatusPayload = \{[\s\S]*upstreamReferenceUrls: upstreamReferenceUrlsForNode,[\s\S]*\}/)
  assert.match(canvasSource, /setNodeStepStatus\(statusIds, baseStatusPayload\)/)
  assert.match(canvasSource, /setNodeStepStatus\(statusIds, \{ \.\.\.baseStatusPayload, promptText \}\)/)
  assert.match(canvasSource, /runImageStep\(drama\.value, latestSb, genOpts, node\?\.data\?\.frameKind \|\| '', taskStatusOptions\)/)
  assert.match(canvasSource, /runVideoStep\(drama\.value, latestSb, genOpts, taskStatusOptions\)/)
  assert.match(canvasSource, /const resultInfo = \{ \.\.\.nodeStepResultInfo\(node, step, sb\.id, refreshedSb\), \.\.\.\(operationResult \|\| \{\}\), promptText \}/)
  assert.match(canvasSource, /errorDetail: errorMessage/)
  assert.match(canvasSource, /upstreamReferenceUrls: upstreamReferenceUrlsForNode/)
})

test('视频节点成功后优先提供尾帧衔接入口', () => {
  assert.match(canvasSource, /function videoNodeNextAction\(storyboard\)/)
  assert.match(canvasSource, /const fallback = \{ nextStep: 'audio', nextLabel: '继续配音' \}/)
  assert.match(canvasSource, /const found = findStoryboardInDrama\(drama\.value, storyboard\.id\)/)
  assert.match(canvasSource, /const \{ next \} = found\?\.episode \? getAdjacentStoryboards\(found\.episode, current\.id\) : \{\}/)
  assert.match(canvasSource, /if \(next && canChainStoryboardFrames\(next, current\)\) \{[\s\S]*nextStep: 'link_tail_frame', nextLabel: '尾帧衔接'/)
  assert.match(canvasSource, /video: videoNodeNextAction\(storyboard\)/)
})

test('右键节点菜单可直接处理结果和失败重试', () => {
  assert.match(contextMenuSource, /title: '结果'/)
  assert.match(contextMenuSource, /type: 'open-node-result'/)
  assert.match(contextMenuSource, /type: 'copy-node-result'/)
  assert.match(contextMenuSource, /type: 'copy-node-asset-ref'/)
  assert.match(contextMenuSource, /type: 'focus-node-result'/)
  assert.match(contextMenuSource, /type: 'retry-node-failed'/)
  assert.match(contextMenuSource, /type: 'continue-node-next-step'/)
  assert.match(contextMenuSource, /继续下游步骤/)
  assert.match(contextMenuSource, /按节点状态继续/)
  assert.match(canvasSource, /function nodeRuntimeStatus\(node\)/)
  assert.match(canvasSource, /function nodeResultUrl\(node, status = nodeRuntimeStatus\(node\)\)/)
  assert.match(canvasSource, /if \(status\?\.savedAssetUrl\) return status\.savedAssetUrl/)
  assert.match(canvasSource, /function resultNodeIdFromStatus\(node, status = nodeRuntimeStatus\(node\)\)/)
  assert.match(canvasSource, /actions\.unshift\('open-node-result', 'copy-node-result'\)/)
  assert.match(canvasSource, /runtimeStatus\?\.savedAssetId/)
  assert.match(canvasSource, /runtimeStatus\?\.nextStep/)
  assert.match(canvasSource, /actions\.unshift\('continue-node-next-step'\)/)
  assert.match(canvasSource, /actions\.unshift\('retry-node-failed'\)/)
  assert.match(canvasSource, /function openNodeResult\(node\)/)
  assert.match(canvasSource, /function copyNodeResult\(node\)/)
  assert.match(canvasSource, /function copyNodeAssetReference\(node\)/)
  assert.match(canvasSource, /function focusNodeResult\(node\)/)
  assert.match(canvasSource, /function retryFailedNode\(node\)/)
  assert.match(canvasSource, /async function continueNodeNextStep\(node\)/)
  assert.match(canvasSource, /await runCanvasNodeStep\(node, status\.nextStep\)/)
  assert.match(canvasSource, /if \(type === 'open-node-result'\)/)
  assert.match(canvasSource, /await copyNodeAssetReference\(node\)/)
  assert.match(canvasSource, /await retryFailedNode\(node\)/)
  assert.match(canvasSource, /type === 'continue-node-next-step'[\s\S]*await continueNodeNextStep\(node\)/)
})

test('画布分镜节点回显并复制已指派素材库参考', () => {
  assert.match(canvasSource, /const storyboardAssignedAssets = ref\(\{\}\)/)
  assert.match(canvasSource, /assignedAssets: storyboardAssignedAssets\.value\[storyboardId\] \|\| \[\]/)
  assert.match(canvasSource, /function nodeAssignedAssets\(node\)/)
  assert.match(canvasSource, /function assetReferenceText\(asset\)/)
  assert.match(canvasSource, /function assignedAssetImagePayload\(asset\)/)
  assert.match(canvasSource, /function copyNodeAssignedAssetReference\(node\)/)
  assert.match(canvasSource, /function unbindNodeAssignedAsset\(node\)/)
  assert.match(canvasSource, /async function setNodeAssignedAssetFrame\(node, frameType\)/)
  assert.match(canvasSource, /'set-assigned-asset-first-frame'/)
  assert.match(canvasSource, /'set-assigned-asset-last-frame'/)
  assert.match(canvasSource, /await copyNodeAssignedAssetReference\(node\)/)
  assert.match(canvasSource, /await unbindNodeAssignedAsset\(node\)/)
  assert.match(canvasSource, /await setNodeAssignedAssetFrame\(node, 'storyboard_first'\)/)
  assert.match(canvasSource, /await setNodeAssignedAssetFrame\(node, 'storyboard_last'\)/)
  assert.match(canvasSource, /assetsAPI\.update\(assetId, \{ storyboard_id: null \}\)/)
  assert.match(canvasSource, /imagesAPI\.upload\(\{[\s\S]*storyboard_id: sb\.id[\s\S]*frame_type: frameType/)
  assert.match(canvasSource, /storyboardAssignedAssets\.value = assets\.reduce/)
  assert.match(canvasSource, /asset\?\.category === 'canvas-result'/)
  assert.match(contextMenuSource, /type: 'copy-node-assigned-asset-ref'/)
  assert.match(contextMenuSource, /复制指派素材/)
  assert.match(contextMenuSource, /type: 'set-assigned-asset-first-frame'/)
  assert.match(contextMenuSource, /设为首帧/)
  assert.match(contextMenuSource, /type: 'set-assigned-asset-last-frame'/)
  assert.match(contextMenuSource, /设为尾帧/)
  assert.match(contextMenuSource, /type: 'unbind-node-assigned-asset'/)
  assert.match(contextMenuSource, /解绑指派素材/)
  assert.match(storyboardNodeSource, /const assignedAssets = computed/)
  assert.match(storyboardNodeSource, /class="reference-strip"/)
  assert.match(storyboardNodeSource, /assetThumbUrl\(asset\)/)
  assert.match(storyboardNodeSource, /ctx\?\.setFocusedNode\?\.\(props\.id\)/)
})

test('画布节点生成成功后自动存入素材库并回填素材引用', () => {
  assert.match(canvasSource, /function resultLocalPathFromUrl\(url\)/)
  assert.match(canvasSource, /function nodeResultAssetName\(node, resultInfo\)/)
  assert.match(canvasSource, /async function saveNodeResultAsset\(node, resultInfo, promptText, storyboardId\)/)
  assert.match(canvasSource, /assetsAPI\.create\(\{[\s\S]*category: 'canvas-result'[\s\S]*source: 'canvas_node_result'[\s\S]*auto_saved: true/)
  assert.match(canvasSource, /const savedAssetInfo = await saveNodeResultAsset\(node, resultInfo, promptText, sb\.id\)/)
  assert.match(canvasSource, /const successPayload = \{ \.\.\.resultInfo, \.\.\.\(savedAssetInfo \|\| \{\}\), runKey, sourceNodeId: nodeId, autoClear: false \}/)
  assert.match(canvasSource, /function successNodeStepStatus\(statusIds, payload\)/)
  assert.match(canvasSource, /statusIds\.forEach\(\(id\) => nodeStatus\.success\(id, payload\)\)/)
  assert.match(canvasSource, /successNodeStepStatus\(statusIds, successPayload\)/)
  assert.match(canvasSource, /savedAssetId: asset\.id/)
  assert.match(canvasSource, /savedAssetName: asset\.name \|\| nodeResultAssetName\(node, resultInfo\)/)
  assert.match(canvasSource, /refreshProjectAssets: async \(\) => \{[\s\S]*await loadProjectImageAssets\(\)[\s\S]*rebuildGraph\(\)/)
  assert.match(overlaySource, /if \(ctx\?\.refreshProjectAssets\) await ctx\.refreshProjectAssets\(\)/)
})

test('手动连线的上游节点结果会作为下游生成参考输入', () => {
  assert.match(canvasSource, /function nodeInputReferenceUrls\(node\)/)
  assert.match(canvasSource, /String\(edge\?\.target \|\| ''\) !== targetId/)
  assert.match(canvasSource, /const sourceNode = findGraphNode\(edge\.source\)/)
  assert.match(canvasSource, /nodeResultUrl\(sourceNode\)/)
  assert.match(canvasSource, /for \(const asset of nodeAssignedAssets\(node\)\) \{/)
  assert.match(canvasSource, /const url = assetDisplayUrl\(asset\)/)
  assert.match(canvasSource, /const upstreamReferenceUrlsForNode = nodeInputReferenceUrls\(node\)/)
  assert.match(canvasSource, /upstreamReferenceUrls: upstreamReferenceUrlsForNode/)
})

test('节点成功状态从刷新后的分镜媒体兜底解析结果地址', () => {
  assert.match(canvasSource, /import \{ assetImageUrl, assetMediaUrl, audioUrl \} from '@\/utils\/mediaUrl'/)
  assert.match(canvasSource, /resolveSbFirstImageRecord/)
  assert.match(canvasSource, /resolveSbLastImageRecord/)
  assert.match(canvasSource, /resolveSbMainImageRecord/)
  assert.match(canvasSource, /resolveSbVideoRecord/)
  assert.match(canvasSource, /function nodeStepResultUrl\(node, step, storyboard\)/)
  assert.match(canvasSource, /if \(frameKind === 'first'\) return imageRecordUrl\(resolveSbFirstImageRecord\(storyboard, imagesBySbId\.value\)\)/)
  assert.match(canvasSource, /if \(frameKind === 'last'\) return imageRecordUrl\(resolveSbLastImageRecord\(storyboard, imagesBySbId\.value\)\)/)
  assert.match(canvasSource, /if \(step === 'video'\) return videoRecordUrl\(resolveSbVideoRecord\(storyboard, videosBySbId\.value\)\)/)
  assert.match(canvasSource, /if \(step === 'audio'\) return audioUrl\(storyboard\.audio_local_path \|\| storyboard\.audio_url \|\| ''\)/)
  assert.match(canvasSource, /const refreshed = findStoryboardInDrama\(drama\.value, sb\.id\)/)
  assert.match(canvasSource, /const refreshedSb = refreshed\?\.storyboard \|\| latestSb/)
})

test('画布节点结果定位和工作流失败状态可恢复重试', () => {
  assert.match(canvasSource, /import \{ taskAPI \} from '@\/api\/task'/)
  assert.match(canvasSource, /function isRestoredPendingNodeStatus\(status\)/)
  assert.match(canvasSource, /function taskResultUrl\(task\)/)
  assert.match(canvasSource, /function restoredNodeStoryboardId\(node, status\)/)
  assert.match(canvasSource, /function restoredTaskResultInfo\(node, status, task, resultUrl\)/)
  assert.match(canvasSource, /async function syncRestoredNodeTasks\(\)/)
  assert.match(canvasSource, /await taskAPI\.get\(status\.taskId\)/)
  assert.match(canvasSource, /const resultUrl = taskResultUrl\(task\) \|\| status\.resultUrl \|\| status\.savedAssetUrl \|\| ''/)
  assert.match(canvasSource, /const resultInfo = restoredTaskResultInfo\(node, status, task, resultUrl\)/)
  assert.match(canvasSource, /const savedAssetInfo = !status\.savedAssetId && resultUrl && storyboardId[\s\S]*await saveNodeResultAsset\(node, resultInfo, resultInfo\.promptText \|\| '', storyboardId\)/)
  assert.match(canvasSource, /nodeStatus\.success\(nodeId, \{[\s\S]*\.\.\.resultInfo,[\s\S]*\.\.\.\(savedAssetInfo \|\| \{\}\),[\s\S]*autoClear: false/)
  assert.match(canvasSource, /nodeStatus\.fail\(nodeId, \{[\s\S]*retryStep: status\.retryStep \|\| status\.step/)
  assert.match(canvasSource, /void syncRestoredNodeTasks\(\)/)
  assert.match(canvasSource, /if \(status\?\.resultNodeId\) return status\.resultNodeId/)
  assert.match(canvasSource, /resultNodeId,/)
  assert.match(canvasSource, /function failNodeStepStatus\(statusIds, payload\)/)
  assert.match(canvasSource, /statusIds\.forEach\(\(id\) => nodeStatus\.fail\(id, payload\)\)/)
  assert.match(canvasSource, /function clearTransientNodeStepStatus\(statusIds\)/)
  assert.match(canvasSource, /if \(!shouldKeepNodeStatus\(id\)\) nodeStatus\.clear\(id\)/)
  assert.match(canvasSource, /failNodeStepStatus\(statusIds, retryPayload\)/)
  assert.match(canvasSource, /clearTransientNodeStepStatus\(statusIds\)/)
  assert.match(canvasSource, /nodeStatus\.set\(`sb:\$\{storyboardId\}`, \{ step, message: label, storyboardId, retryStep: step \}\)/)
  assert.match(canvasSource, /nodeStatus\.fail\(`sb:\$\{storyboardId\}`, \{[\s\S]*retryStep: step[\s\S]*retryLabel: `重试\$\{CANVAS_NODE_STATUS_LABELS\[step\] \|\| step\}`/)
  assert.match(canvasSource, /retryStep: queueNodeRetryStep\(findGraphNode\(`sb:\$\{storyboardId\}`\)\) \|\| 'video'/)
})

test('运行队列区分成功状态并提供结果操作', () => {
  assert.match(canvasSource, /successQueueCount/)
  assert.match(canvasSource, /\{\{ runningQueueCount \}\} 进行中 · \{\{ successQueueCount \}\} 完成 · \{\{ failedQueueCount \}\} 异常/)
  assert.match(canvasSource, /const grouped = new Map\(\)/)
  assert.match(canvasSource, /const key = `active:\$\{queueStatusRunKey\(nodeId, status\)\}`/)
  assert.match(canvasSource, /const sourceNodeId = status\.sourceNodeId \|\| nodeId/)
  assert.match(canvasSource, /nodeId: sourceNodeId/)
  assert.match(canvasSource, /label: queueNodeLabel\(sourceNodeId\)/)
  assert.match(canvasSource, /function queueStatusRunKey\(nodeId, status\)/)
  assert.match(canvasSource, /return status\?\.runKey \|\| `node:\$\{nodeId\}`/)
  assert.match(canvasSource, /function mergeRunQueueItem\(grouped, item\)/)
  assert.match(canvasSource, /current\.statusIds = \[\.\.\.new Set\(\[\.\.\.\(current\.statusIds \|\| \[\]\), \.\.\.\(item\.statusIds \|\| \[\]\)\]\)\]/)
  assert.match(canvasSource, /tone: isFailed \? 'failed' : isSuccess \? 'success' : 'running'/)
  assert.match(canvasSource, /function queueSuccessMessage\(status\)/)
  assert.match(canvasSource, /function queueResultPreviewType\(item\)/)
  assert.match(canvasSource, /class="run-result-preview"/)
  assert.match(canvasSource, /'preview-' \+ queueResultPreviewType\(item\)/)
  assert.match(canvasSource, /<img v-if="item\.resultUrl && queueResultPreviewType\(item\) === 'image'"/)
  assert.match(canvasSource, /<video v-else-if="item\.resultUrl && queueResultPreviewType\(item\) === 'video'"/)
  assert.match(canvasSource, /<span v-else-if="item\.resultUrl" class="audio-preview">/)
  assert.match(canvasSource, /@click\.stop="item\.resultUrl && openQueueItemResult\(item\)"/)
  assert.match(canvasSource, /status\.retryStep \|\| queueNodeRetryStep\(findGraphNode\(sourceNodeId\)\)/)
  assert.match(canvasSource, /function openQueueItemResult\(item\)/)
  assert.match(canvasSource, /function copyQueueItemResult\(item\)/)
  assert.match(canvasSource, /function focusQueueItemResult\(item\)/)
  assert.match(canvasSource, /function dismissQueueItem\(item\)/)
  assert.match(canvasSource, /const ids = item\?\.statusIds\?\.length \? item\.statusIds : \[item\?\.nodeId\]/)
  assert.match(canvasSource, /ids\.filter\(Boolean\)\.forEach\(\(id\) => nodeStatus\.clear\(id\)\)/)
  assert.match(canvasSource, /class="run-success-actions"/)
})

test('媒体节点卡片从运行状态恢复结果、失败原因和重试步骤', () => {
  assert.match(mediaNodeSource, /const runtimeStatus = computed\(\(\) => ctx\?\.nodeStatus\?\.map\?\.\[props\.id\] \|\| null\)/)
  assert.match(mediaNodeSource, /const imagesBySbId = computed\(\(\) => ctx\?\.imagesBySbId\?\.value \|\| \{\}\)/)
  assert.match(mediaNodeSource, /const videosBySbId = computed\(\(\) => ctx\?\.videosBySbId\?\.value \|\| \{\}\)/)
  assert.match(mediaNodeSource, /const fallbackResultUrl = computed\(\(\) => \{/)
  assert.match(mediaNodeSource, /props\.data\.frameKind === 'first'[\s\S]*resolveSbFirstImageRecord\(sb, imagesBySbId\.value\)/)
  assert.match(mediaNodeSource, /props\.data\.frameKind === 'last'[\s\S]*resolveSbLastImageRecord\(sb, imagesBySbId\.value\)/)
  assert.match(mediaNodeSource, /resolveSbMainImageRecord\(sb, imagesBySbId\.value\)/)
  assert.match(mediaNodeSource, /videoRecordUrl\(props\.data\.videoRecord \|\| resolveSbVideoRecord\(sb, videosBySbId\.value\)\)/)
  assert.match(mediaNodeSource, /sb\.audio_local_path[\s\S]*sb\.audio_url[\s\S]*sb\.narration_audio_local_path[\s\S]*sb\.narration_audio_url/)
  assert.match(mediaNodeSource, /const resultUrl = computed\(\(\) => runtimeStatus\.value\?\.resultUrl \|\| props\.data\.url \|\| fallbackResultUrl\.value\)/)
  assert.match(mediaNodeSource, /const isRecoveredResult = computed/)
  assert.match(mediaNodeSource, /key: 'recovered', label: '已恢复'/)
  assert.match(mediaNodeSource, /status\?\.errorDetail \|\| status\?\.detail/)
  assert.match(mediaNodeSource, /failureReason\.value/)
  assert.match(mediaNodeSource, /runtimeStatus\.value\?\.retryStep \|\| props\.data\.kind/)
  assert.match(mediaNodeSource, /<img v-if="resultUrl" :src="resultUrl"/)
  assert.match(mediaNodeSource, /<video v-if="resultUrl" :src="resultUrl"/)
  assert.match(mediaNodeSource, /:generation-error="failureReason"/)
})

test('资产节点卡片显示参考图失败原因并可重试', () => {
  assert.match(assetNodeSource, /import \{ isCanvasNodeBusyStatus \} from '@\/utils\/canvasNodeStatus'/)
  assert.match(assetNodeSource, /const runtimeStatus = computed\(\(\) => ctx\?\.nodeStatus\?\.map\?\.\[props\.id\] \|\| null\)/)
  assert.match(assetNodeSource, /isCanvasNodeBusyStatus\(runtimeStatus\.value\)/)
  assert.match(assetNodeSource, /const failureReason = computed/)
  assert.match(assetNodeSource, /status\?\.errorDetail/)
  assert.match(assetNodeSource, /entity\.generation_error/)
  assert.match(assetNodeSource, /class="asset-error"/)
  assert.match(assetNodeSource, /const retryStep = computed\(\(\) => runtimeStatus\.value\?\.retryStep \|\| 'ref_image'\)/)
  assert.match(assetNodeSource, /function retryAsset\(\)/)
  assert.match(assetNodeSource, /ctx\?\.runNodeStep\?\.\(\{ id: props\.id, type: 'canvasAsset', data: props\.data \}, retryStep\.value\)/)
  assert.match(canvasSource, /if \(node\?\.type === 'canvasAsset'\) \{[\s\S]*await runCanvasAssetNodeStep\(node, step\)/)
  assert.match(canvasSource, /async function runCanvasAssetNodeStep\(node, step\)/)
  assert.match(canvasSource, /await generateAssetReferenceImage\([\s\S]*\{ nodeStatus, drama, refreshDrama, refresh: refreshCanvas \}/)
  assert.match(assetGenerateSource, /retryStep: step/)
  assert.match(assetGenerateSource, /retryLabel: '重试参考图'/)
  assert.match(assetGenerateSource, /nodeStatus\?\.fail\(nodeId, \{/)
  assert.match(assetGenerateSource, /errorDetail: message/)
})

test('脚本节点卡片显示保存和提取失败原因并可按步骤重试', () => {
  assert.match(scriptNodeSource, /import \{ isCanvasNodeBusyStatus \} from '@\/utils\/canvasNodeStatus'/)
  assert.match(scriptNodeSource, /const runtimeStatus = computed\(\(\) => ctx\?\.nodeStatus\?\.map\?\.\[props\.id\] \|\| null\)/)
  assert.match(scriptNodeSource, /isCanvasNodeBusyStatus\(runtimeStatus\.value\)/)
  assert.match(scriptNodeSource, /const failureReason = computed/)
  assert.match(scriptNodeSource, /status\?\.errorDetail/)
  assert.match(scriptNodeSource, /class="script-error"/)
  assert.match(scriptNodeSource, /const retryStep = computed\(\(\) => runtimeStatus\.value\?\.retryStep \|\| ''\)/)
  assert.match(scriptNodeSource, /function retryScript\(\)/)
  assert.match(scriptNodeSource, /retryStep\.value === 'save_script'/)
  assert.match(scriptNodeSource, /api\?\.saveScript\?\.\(episodeId, \{ scriptContent, title \}\)/)
  assert.match(scriptNodeSource, /retryStep\.value === 'extract_chars'/)
  assert.match(scriptNodeSource, /api\?\.extractCharacters\?\.\(episodeId, scriptContent\)/)
  assert.match(scriptNodeSource, /retryStep\.value === 'extract_scenes'/)
  assert.match(scriptNodeSource, /retryStep\.value === 'extract_props'/)
  assert.match(scriptNodeSource, /retryStep\.value === 'extract_all'/)
  assert.match(scriptActionsSource, /function failScriptStatus\(episodeId, step, error\)/)
  assert.match(scriptActionsSource, /nodeStatus\?\.fail\(scriptNodeId\(episodeId\), \{/)
  assert.match(scriptActionsSource, /retryStep: step/)
  assert.match(scriptActionsSource, /function successScriptStatus\(episodeId, step, message\)/)
  assert.match(scriptActionsSource, /nodeStatus\?\.success\(scriptNodeId\(episodeId\), \{/)
  assert.match(scriptActionsSource, /keepOrClearScriptStatus\(episodeId\)/)
})

test('项目素材节点卡片可预览并复制素材引用', () => {
  assert.match(projectAssetNodeSource, /class="asset-actions"/)
  assert.match(projectAssetNodeSource, /@click\.stop="openAsset"/)
  assert.match(projectAssetNodeSource, /@click\.stop="copyReference"/)
  assert.match(projectAssetNodeSource, /@click\.stop="assignToSelectedStoryboard"/)
  assert.match(projectAssetNodeSource, /import \{ assetMediaUrl \} from '@\/utils\/mediaUrl'/)
  assert.match(projectAssetNodeSource, /assetType === 'video'/)
  assert.match(projectAssetNodeSource, /assetType === 'audio'/)
  assert.match(projectAssetNodeSource, /const url = computed\(\(\) => assetMediaUrl\(props\.data\.asset\)\)/)
  assert.match(projectAssetNodeSource, /const referenceText = computed/)
  assert.match(projectAssetNodeSource, /const assetId = computed/)
  assert.match(projectAssetNodeSource, /@素材\(\$\{name\}#\$\{asset\.id\}\)/)
  assert.match(projectAssetNodeSource, /window\.open\(url\.value, '_blank', 'noopener,noreferrer'\)/)
  assert.match(projectAssetNodeSource, /navigator\.clipboard\?\.writeText/)
  assert.match(projectAssetNodeSource, /ElMessage\.success\('素材引用已复制'\)/)
  assert.match(projectAssetNodeSource, /ElMessageBox\.alert\(referenceText\.value, '素材引用（请手动复制）'/)
  assert.match(projectAssetNodeSource, /function assignToSelectedStoryboard\(\)/)
  assert.match(projectAssetNodeSource, /import CanvasNodeStatusOverlay from '\.\/CanvasNodeStatusOverlay\.vue'/)
  assert.match(projectAssetNodeSource, /<CanvasNodeStatusOverlay :node-id="id" \/>/)
  assert.match(projectAssetNodeSource, /ctx\?\.runNodeStep\?\.\(\{ id: props\.id, type: 'canvasProjectAsset', data: props\.data \}, 'library'\)/)
  assert.match(canvasSource, /function assetReferenceText\(asset\)/)
  assert.match(canvasSource, /assetMediaUrl\(node\.data\?\.asset\)/)
  assert.match(canvasSource, /function assetDisplayUrl\(asset\)/)
  assert.match(canvasSource, /@素材\(\$\{name\}#\$\{asset\.id\}\)/)
})

test('项目素材节点可直接指派到当前选中分镜', () => {
  assert.match(canvasSource, /function projectAssetId\(asset\)/)
  assert.match(canvasSource, /async function assignProjectAssetToSelectedStoryboard\(asset, options = \{\}\)/)
  assert.match(canvasSource, /const silent = options\.silent === true/)
  assert.match(canvasSource, /const returnDetail = options\.returnDetail === true/)
  assert.match(canvasSource, /const fail = \(message\) => \{[\s\S]*return returnDetail \? \{ ok: false, message \} : false/)
  assert.match(canvasSource, /缺少项目 ID，无法指派素材/)
  assert.match(canvasSource, /async function runCanvasProjectAssetNodeStep\(node, step\)/)
  assert.match(canvasSource, /if \(step !== 'library'\)/)
  assert.match(canvasSource, /nodeStatus\.set\(nodeId, \{[\s\S]*step: 'library'[\s\S]*指派素材到分镜中/)
  assert.match(canvasSource, /await assignProjectAssetToSelectedStoryboard\(asset, \{ silent: true, returnDetail: true \}\)/)
  assert.match(canvasSource, /throw new Error\(result\?\.message \|\| '素材未指派，请选中一个分镜后重试'\)/)
  assert.match(canvasSource, /nodeStatus\.success\(nodeId, \{[\s\S]*已指派素材到选中分镜/)
  assert.match(canvasSource, /retryStep: 'library'/)
  assert.match(canvasSource, /nodeStatus\.fail\(nodeId, \{[\s\S]*\.\.\.retryPayload/)
  assert.match(canvasSource, /selectedStoryboardIds\.value\.map\(Number\)\.filter\(Number\.isFinite\)/)
  assert.match(canvasSource, /selectedIds\.length !== 1/)
  assert.match(canvasSource, /assetsAPI\.update\(assetId, \{ drama_id: drama\.value\.id, storyboard_id: storyboardId \}\)/)
  assert.match(canvasSource, /await loadProjectImageAssets\(\)/)
  assert.match(canvasSource, /await focusCanvasNode\(`sb:\$\{storyboardId\}`\)/)
  assert.match(canvasSource, /assignProjectAssetToSelectedStoryboard,/)
  assert.match(canvasSource, /actions\.unshift\('assign-project-asset-selected'\)/)
  assert.match(canvasSource, /await runCanvasNodeStep\(node, 'library'\)/)
  assert.match(contextMenuSource, /type: 'assign-project-asset-selected'/)
  assert.match(contextMenuSource, /指派到选中分镜/)
})
