import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const canvasSource = readFileSync(fileURLToPath(new URL('../src/views/DramaCanvas.vue', import.meta.url)), 'utf8')
const contextMenuSource = readFileSync(fileURLToPath(new URL('../src/components/dramaCanvas/CanvasContextMenu.vue', import.meta.url)), 'utf8')
const storyboardPanelSource = readFileSync(fileURLToPath(new URL('../src/components/dramaCanvas/CanvasStoryboardPanel.vue', import.meta.url)), 'utf8')
const assetPanelSource = readFileSync(fileURLToPath(new URL('../src/components/dramaCanvas/CanvasAssetPanel.vue', import.meta.url)), 'utf8')
const mediaPanelSource = readFileSync(fileURLToPath(new URL('../src/components/dramaCanvas/CanvasMediaPanel.vue', import.meta.url)), 'utf8')
const dramaCanvasAdapterSource = readFileSync(fileURLToPath(new URL('../src/utils/dramaCanvasAdapter.js', import.meta.url)), 'utf8')
const storyboardNodeSource = readFileSync(fileURLToPath(new URL('../src/components/dramaCanvas/CanvasStoryboardNode.vue', import.meta.url)), 'utf8')
const mediaNodeSource = readFileSync(fileURLToPath(new URL('../src/components/dramaCanvas/CanvasMediaNode.vue', import.meta.url)), 'utf8')
const assetNodeSource = readFileSync(fileURLToPath(new URL('../src/components/dramaCanvas/CanvasAssetNode.vue', import.meta.url)), 'utf8')
const scriptNodeSource = readFileSync(fileURLToPath(new URL('../src/components/dramaCanvas/CanvasScriptNode.vue', import.meta.url)), 'utf8')
const scriptPanelSource = readFileSync(fileURLToPath(new URL('../src/components/dramaCanvas/CanvasScriptPanel.vue', import.meta.url)), 'utf8')
const storyboardImageUploadSource = readFileSync(fileURLToPath(new URL('../src/components/dramaCanvas/CanvasStoryboardImageUpload.vue', import.meta.url)), 'utf8')
const projectAssetNodeSource = readFileSync(fileURLToPath(new URL('../src/components/dramaCanvas/CanvasProjectAssetNode.vue', import.meta.url)), 'utf8')
const nodeStatusOverlaySource = readFileSync(fileURLToPath(new URL('../src/components/dramaCanvas/CanvasNodeStatusOverlay.vue', import.meta.url)), 'utf8')
const nodeExecutionStripSource = readFileSync(fileURLToPath(new URL('../src/components/dramaCanvas/CanvasNodeExecutionStrip.vue', import.meta.url)), 'utf8')

test('右键节点菜单保留配置面板入口', () => {
  assert.match(contextMenuSource, /type: 'open-node-config'/)
  assert.match(contextMenuSource, /打开节点配置/)
  assert.match(contextMenuSource, /type: 'open-node-production'/)
  assert.match(contextMenuSource, /进入制作页/)
  assert.match(canvasSource, /if \(type === 'open-node-config'\) \{/)
  assert.match(canvasSource, /openNodeConfig\(node\)/)
  assert.match(canvasSource, /else if \(type === 'open-node-production'\) \{[\s\S]*onNodeDoubleClick\(\{ node \}\)/)
  assert.match(canvasSource, /function canOpenNodeProduction\(node\)/)
  assert.match(canvasSource, /if \(canOpenNodeProduction\(node\)\) actions\.unshift\('open-node-production'\)/)
  assert.match(canvasSource, /function openNodeConfig\(node\)/)
  assert.match(canvasSource, /PANEL_NODE_TYPES\.has\(node\.type\)[\s\S]*focusedNodeId\.value = node\.id/)
  assert.match(canvasSource, /'canvasProjectAsset'/)
  assert.match(canvasSource, /async function focusCanvasNodeWithConfig\(nodeId, warning = ''\)/)
  assert.match(canvasSource, /const node = findGraphNode\(nodeId\)/)
  assert.match(canvasSource, /await focusCanvasNode\(nodeId\)/)
  assert.match(canvasSource, /if \(PANEL_NODE_TYPES\.has\(node\.type\)\) openNodeConfig\(node\)/)
  assert.match(canvasSource, /async function focusQueueItem\(item\) \{[\s\S]*await focusCanvasNodeWithConfig\(item\.nodeId\)/)
  assert.match(canvasSource, /async function focusNodeOrWarn\(nodeId, warning\) \{[\s\S]*return focusCanvasNodeWithConfig\(nodeId, warning\)/)
})

test('脚本素材媒体节点支持单击聚焦并打开配置面板', () => {
  for (const source of [mediaNodeSource, assetNodeSource, scriptNodeSource]) {
    assert.match(source, /@click\.stop="onSelect"/)
    assert.match(source, /function onSelect\(\) \{[\s\S]*ctx\?\.setFocusedNode\?\.\(props\.id\)[\s\S]*\}/)
  }
  assert.match(mediaNodeSource, /<CanvasMediaPanel[\s\S]*v-if="showPanel"/)
  assert.match(assetNodeSource, /<CanvasAssetPanel[\s\S]*v-if="showPanel"/)
  assert.match(scriptNodeSource, /<CanvasScriptPanel[\s\S]*v-if="showPanel"/)
})

test('脚本配置面板保存后保留节点状态和失败重试', () => {
  assert.match(scriptPanelSource, /<CanvasNodeExecutionStrip/)
  assert.match(scriptPanelSource, /:status="activeNodeStatus"/)
  assert.match(scriptPanelSource, /@retry="retryScriptFailedStep"/)
  assert.match(scriptPanelSource, /ctx\?\.nodeStatus\?\.set\(props\.nodeId, \{ step: 'save', message: '剧本保存中…' \}\)/)
  assert.match(scriptPanelSource, /await ctx\?\.refreshDrama\?\.\(true\)/)
  assert.match(scriptPanelSource, /ctx\?\.nodeStatus\?\.success\(props\.nodeId, \{/)
  assert.match(scriptPanelSource, /resultType: 'text'/)
  assert.match(scriptPanelSource, /resultLabel: '剧本已保存'/)
  assert.match(scriptPanelSource, /promptText: form\.scriptContent/)
  assert.match(scriptPanelSource, /autoClear: false/)
  assert.match(scriptPanelSource, /ctx\?\.nodeStatus\?\.fail\(props\.nodeId, \{/)
  assert.match(scriptPanelSource, /errorDetail: message/)
  assert.match(scriptPanelSource, /retryStep: 'save'/)
  assert.match(scriptPanelSource, /retryLabel: '重试保存剧本'/)
  assert.match(scriptPanelSource, /recoverable: true/)
  assert.match(scriptPanelSource, /async function retryScriptFailedStep\(\)/)
  assert.match(scriptPanelSource, /step === 'extract_characters'/)
  assert.match(scriptPanelSource, /retryLabel = '重试提取'/)
  assert.match(scriptPanelSource, /retryStep: step/)
})

test('分镜配置面板保留保存、回显刷新和单镜模型配置', () => {
  assert.match(storyboardPanelSource, /function saveFields\(\)/)
  assert.match(storyboardPanelSource, /await persistForm\(false\)/)
  assert.match(storyboardPanelSource, /await ctx\?\.refreshDrama\?\.\(true\)/)
  assert.match(storyboardPanelSource, /actionStatus\.value = \{ type: 'success', message: '保存完成' \}/)
  assert.match(storyboardPanelSource, />恢复</)
  assert.match(storyboardPanelSource, /function resetFields\(\)/)
  assert.match(storyboardPanelSource, /syncForm\(props\.storyboard\)/)
  assert.match(storyboardPanelSource, /已恢复到上次保存/)
  assert.match(storyboardPanelSource, /CanvasGenerationOptions/)
  assert.match(storyboardPanelSource, /function saveStoryboardGenerationOptions\(patch, next\)/)
  assert.match(storyboardPanelSource, /const videoModel = ref\(''\)/)
  assert.match(storyboardPanelSource, /videoModel\.value \|\| projectGenerationOptions\.value\.videoModel/)
  assert.match(storyboardPanelSource, /videoModel\.value = Object\.prototype\.hasOwnProperty\.call\(sb \|\| \{\}, 'video_model'\) \? sb\?\.video_model \|\| '' : ''/)
  assert.match(storyboardPanelSource, /videoModel\.value = String\(next\.videoModel \|\| ''\)\.trim\(\)/)
  assert.match(storyboardPanelSource, /runVideoStep\(drama, sb, \{[\s\S]*videoModel: videoModel\.value \|\| genOpts\.videoModel/)
})

test('节点配置面板支持完整生成参数而非只改模型', () => {
  assert.doesNotMatch(storyboardPanelSource, /<CanvasGenerationOptions[\s\S]*models-only[\s\S]*@change="saveStoryboardGenerationOptions"[\s\S]*\/>/)
  assert.match(storyboardPanelSource, /label="生成参数"/)
  assert.match(storyboardPanelSource, /模型 \/ 画幅 \/ 清晰度 \/ 时长/)
  assert.match(storyboardPanelSource, /画幅与清晰度保存为项目生成参数/)
  assert.match(storyboardPanelSource, /Object\.hasOwn\(patch, 'aspectRatio'\)/)
  assert.match(storyboardPanelSource, /Object\.hasOwn\(patch, 'videoResolution'\)/)
  assert.match(storyboardPanelSource, /Object\.hasOwn\(patch, 'videoDuration'\)/)
  assert.match(storyboardPanelSource, /payload\.duration = form\.duration/)
  assert.match(storyboardPanelSource, /ctx\?\.updateGenerationOptions\?\.\(/)
  assert.doesNotMatch(mediaPanelSource, /<CanvasGenerationOptions[\s\S]*models-only[\s\S]*@change="saveStoryboardGenerationOptions"[\s\S]*\/>/)
  assert.match(mediaPanelSource, /label="生成参数"/)
  assert.match(mediaPanelSource, /Object\.hasOwn\(patch, 'aspectRatio'\)/)
  assert.match(mediaPanelSource, /Object\.hasOwn\(patch, 'videoResolution'\)/)
  assert.match(mediaPanelSource, /Object\.hasOwn\(patch, 'videoDuration'\)/)
  assert.match(mediaPanelSource, /payload\.duration = Number\(next\.videoDuration\) \|\| 5/)
  assert.match(mediaPanelSource, /videoDuration: universalPromptDuration\(props\.storyboard\)/)
  assert.match(mediaPanelSource, /ctx\?\.updateGenerationOptions\?\.\(/)
})

test('分镜配置面板保留素材库指派、摄影控制、声音策略和连续性入口', () => {
  assert.match(storyboardPanelSource, /从素材库指派参考图/)
  assert.match(storyboardPanelSource, /command="first_frame"/)
  assert.match(storyboardPanelSource, /command="last_frame"/)
  assert.match(storyboardPanelSource, /command="video"/)
  assert.match(storyboardPanelSource, /command="audio"/)
  assert.match(storyboardPanelSource, /:type="assetLibraryType"/)
  assert.match(storyboardPanelSource, /:title="assetLibraryTitle"/)
  assert.match(storyboardPanelSource, /:drama-id="ctx\?\.drama\?\.value\?\.id"/)
  assert.match(storyboardPanelSource, /function onAssetLibraryPick\(asset\)/)
  assert.match(storyboardPanelSource, /function assetAttachStatusIds\(target, storyboardId\)/)
  assert.match(storyboardPanelSource, /ids\.push\(`sbimg-first:\$\{storyboardId\}`\)/)
  assert.match(storyboardPanelSource, /ids\.push\(`sbimg-last:\$\{storyboardId\}`\)/)
  assert.match(storyboardPanelSource, /ids\.push\(`sbvid:\$\{storyboardId\}`\)/)
  assert.match(storyboardPanelSource, /ids\.push\(`sbaud:\$\{storyboardId\}:dialogue`\)/)
  assert.match(storyboardPanelSource, /function assetAttachStatusPayload\(target, asset, message\)/)
  assert.match(storyboardPanelSource, /resultType: assetAttachResultType\(target, asset\)/)
  assert.match(storyboardPanelSource, /function assetLocalPath\(a\)/)
  assert.match(storyboardPanelSource, /a\?\.file_path/)
  assert.match(storyboardPanelSource, /a\?\.thumbnail_local_path/)
  assert.match(storyboardPanelSource, /dramaId: ctx\?\.drama\?\.value\?\.id \|\| undefined/)
  assert.match(storyboardPanelSource, /savedAssetLocalPath: localPath \|\| undefined/)
  assert.match(storyboardPanelSource, /const savedAssetId = target === 'reference' \|\| asset\?\.source_kind === 'project' \|\| String\(asset\?\.id \|\| ''\)\.startsWith\('project:'\)/)
  assert.match(storyboardPanelSource, /setAssetAttachStatus\(target, storyboardId, assetAttachStatusPayload\(target, asset, '素材库挂载中…'\)\)/)
  assert.match(storyboardPanelSource, /setAssetAttachStatus\(target, storyboardId, assetAttachStatusPayload\(target, asset, message\), 'success'\)/)
  assert.match(storyboardPanelSource, /setAssetAttachStatus\(target, storyboardId, assetAttachStatusPayload\(target, savedAsset, ASSET_ATTACH_TARGETS\.reference\.message\), 'success'\)/)
  assert.match(storyboardPanelSource, /function assetAttachFailurePayload\(target, asset, message\)/)
  assert.match(storyboardPanelSource, /attachedSlot: assetAttachSlot\(target\)/)
  assert.match(storyboardPanelSource, /retryStep: ''/)
  assert.match(storyboardPanelSource, /retryLabel: ''/)
  assert.match(storyboardPanelSource, /retryActionLabel: retryAction \? assetAttachRetryLabel\(target\) : ''/)
  assert.match(storyboardPanelSource, /libraryAsset: asset/)
  assert.match(storyboardPanelSource, /function assetAttachRetryAction\(target, resultType\)/)
  assert.match(storyboardPanelSource, /return 'attach_library_image'/)
  assert.match(storyboardPanelSource, /return 'attach_library_video'/)
  assert.match(storyboardPanelSource, /return 'attach_library_audio'/)
  assert.match(storyboardPanelSource, /function assetAttachSlot\(target\)/)
  assert.match(storyboardPanelSource, /if \(target === 'first_frame'\) return 'first'/)
  assert.match(storyboardPanelSource, /if \(target === 'last_frame'\) return 'last'/)
  assert.match(storyboardPanelSource, /setAssetAttachStatus\(target, storyboardId, assetAttachFailurePayload\(target, asset, message\), 'fail'\)/)
  assert.match(storyboardPanelSource, /assetsAPI\.update\(projectAssetId\(asset\), \{ drama_id: dramaId, storyboard_id: storyboardId \}\)/)
  assert.match(storyboardPanelSource, /assetsAPI\.create\(\{[\s\S]*storyboard_id: storyboardId[\s\S]*category: 'storyboard_reference'/)
  assert.match(storyboardPanelSource, /assetsAPI\.list\(\{ storyboard_id: sbId, page: 1, page_size: 20 \}\)/)
  assert.doesNotMatch(storyboardPanelSource, /assetsAPI\.list\(\{ storyboard_id: sbId, type: 'image'/)
  assert.match(storyboardPanelSource, /type: asset\.type \|\| 'image'/)
  assert.match(storyboardPanelSource, /<video v-if="reference\.type === 'video'"/)
  assert.match(storyboardPanelSource, /v-else-if="reference\.type === 'audio'"/)
  assert.match(storyboardPanelSource, /await loadAssignedAssets\(\)/)
  assert.match(storyboardPanelSource, /normalizeAssignedAsset\(savedAsset\)/)
  assert.match(storyboardPanelSource, /camera-control-strip/)
  assert.match(storyboardPanelSource, /function savePhotography\(\)/)
  assert.match(storyboardPanelSource, /gridFrameType\.value/)
  assert.match(storyboardPanelSource, /视频模型与声音/)
  assert.match(storyboardPanelSource, /buildVoicePromptPreview/)
  assert.match(storyboardPanelSource, /固化到视频词/)
  assert.match(storyboardPanelSource, /appendVoicePromptToVideoPrompt\(\{[\s\S]*prompt: form\.video_prompt \|\| form\.universal_segment_text \|\| form\.image_prompt \|\| form\.action \|\| ''/)
  assert.match(storyboardPanelSource, /const canApplyVoicePrompt = computed\(\(\) => \{/)
  assert.match(storyboardPanelSource, /async function applyVoicePromptToVideoPrompt\(\)/)
  assert.match(storyboardPanelSource, /form\.video_prompt = nextPrompt/)
  assert.match(storyboardPanelSource, /await storyboardsAPI\.update\(props\.storyboard\.id, \{ video_prompt: nextPrompt \}\)/)
  assert.match(storyboardPanelSource, /镜头连续性/)
  assert.match(storyboardPanelSource, /function linkTailFrame\(\)/)
  assert.match(storyboardPanelSource, /ctx\?\.nodeStatus\?\.set\(sbNodeId\.value, \{ step: 'link_tail_frame', message: '尾帧衔接中…' \}\)/)
  assert.match(storyboardPanelSource, /ctx\?\.nodeStatus\?\.fail\(sbNodeId\.value, \{[\s\S]*retryStep: 'link_tail_frame'[\s\S]*retryLabel: '重试尾帧衔接'/)
  assert.match(storyboardPanelSource, /errorDetail: errorMessage/)
  assert.match(storyboardPanelSource, /imagesBySbId: ctx\?\.imagesBySbId\?\.value \|\| \{\}/)
  assert.match(storyboardPanelSource, /videosBySbId: ctx\?\.videosBySbId\?\.value \|\| \{\}/)
})

test('分镜配置面板支持素材库按用途挂载到分镜字段', () => {
  assert.match(storyboardPanelSource, /const assetAttachTarget = ref\('reference'\)/)
  assert.match(storyboardPanelSource, /const ASSET_ATTACH_TARGETS = \{/)
  assert.match(storyboardPanelSource, /function openAssetLibrary\(target = 'reference'\)/)
  assert.match(storyboardPanelSource, /assetAttachTarget\.value = ASSET_ATTACH_TARGETS\[target\] \? target : 'reference'/)
  assert.match(storyboardPanelSource, /async function attachPickedAssetToStoryboard\(target, asset\)/)
  assert.match(storyboardPanelSource, /payload\.first_frame_image_id = null/)
  assert.match(storyboardPanelSource, /payload\.image_url = localPath \? null : url/)
  assert.match(storyboardPanelSource, /payload\.local_path = localPath \|\| null/)
  assert.match(storyboardPanelSource, /payload\.last_frame_image_id = null/)
  assert.match(storyboardPanelSource, /payload\.last_frame_image_url = localPath \? null : url/)
  assert.match(storyboardPanelSource, /payload\.last_frame_local_path = localPath \|\| null/)
  assert.match(storyboardPanelSource, /payload\.video_url = url/)
  assert.match(storyboardPanelSource, /payload\.audio_local_path = localPath \|\| undefined/)
  assert.match(storyboardPanelSource, /payload\.audio_url = localPath \? undefined : url/)
  assert.match(storyboardPanelSource, /await storyboardsAPI\.update\(storyboardId, payload\)/)
})

test('分镜首尾帧素材库引用兼容统一素材字段并保留失败状态', () => {
  assert.match(storyboardImageUploadSource, /function libraryAssetUrl\(asset\)/)
  assert.match(storyboardImageUploadSource, /asset\?\.asset_url/)
  assert.match(storyboardImageUploadSource, /asset\?\.image_url/)
  assert.match(storyboardImageUploadSource, /asset\?\.ref_image/)
  assert.match(storyboardImageUploadSource, /asset\?\.thumbnail_url/)
  assert.match(storyboardImageUploadSource, /function libraryAssetLocalPath\(asset\)/)
  assert.match(storyboardImageUploadSource, /asset\?\.image_local_path/)
  assert.match(storyboardImageUploadSource, /asset\?\.thumbnail_local_path/)
  assert.match(storyboardImageUploadSource, /const url = libraryAssetUrl\(asset\)/)
  assert.match(storyboardImageUploadSource, /const localPath = libraryAssetLocalPath\(asset\)/)
  assert.match(storyboardImageUploadSource, /retryAction: 'attach_library_image'/)
  assert.match(storyboardImageUploadSource, /attachedSlot: slot === 'first' \? 'first' : slot === 'last' \? 'last' : 'image'/)
  assert.match(storyboardImageUploadSource, /if \(!failed\) statusIds\.forEach\(\(id\) => ctx\?\.nodeStatus\?\.clear\(id\)\)/)
})

test('分镜配置面板生成成功后保留节点结果回显', () => {
  assert.match(storyboardPanelSource, /function panelNodeStatusIds\(step, sbId\)/)
  assert.match(storyboardPanelSource, /ids\.push\(`sbimg:\$\{sbId\}`\)/)
  assert.match(storyboardPanelSource, /ids\.push\(`sbvid:\$\{sbId\}`\)/)
  assert.match(storyboardPanelSource, /ids\.push\(`sbaud:\$\{sbId\}:dialogue`\)/)
  assert.match(storyboardPanelSource, /function panelGenerationReferenceUrls\(\)/)
  assert.match(storyboardPanelSource, /upstreamReferenceUrls: panelGenerationReferenceUrls\(\)/)
  assert.match(storyboardPanelSource, /function panelSuccessPayload\(step, sb, message, operationResult = \{\}\)/)
  assert.match(storyboardPanelSource, /const resultPatch = Object\.fromEntries\(/)
  assert.match(storyboardPanelSource, /value !== '' && value !== undefined && value !== null/)
  assert.match(storyboardPanelSource, /resultUrl: panelResultUrl\(step, sb\)/)
  assert.match(storyboardPanelSource, /resultType: step/)
  assert.match(storyboardPanelSource, /resultNodeId: panelResultNodeId\(step, sb\?\.id\)/)
  assert.match(storyboardPanelSource, /promptText: panelPromptText\(step, sb\)/)
  assert.match(storyboardPanelSource, /autoClear: false/)
  assert.match(storyboardPanelSource, /\.\.\.resultPatch/)
  assert.match(storyboardPanelSource, /setPanelNodeStatus\(statusIds, panelSuccessPayload\(step, refreshedSb, successMsg, operationResult\), 'success'\)/)
  assert.match(storyboardPanelSource, /function shouldKeepPanelNodeStatus\(id\)/)
  assert.match(storyboardPanelSource, /statusStep === 'failed' \|\| statusStep === 'success'/)
  assert.match(storyboardPanelSource, /if \(!shouldKeepPanelNodeStatus\(id\)\) ctx\?\.nodeStatus\?\.clear\(id\)/)
})

test('资产配置面板保留保存、素材库选图和关联分镜入口', () => {
  assert.match(assetPanelSource, /<CanvasNodeExecutionStrip/)
  assert.match(assetPanelSource, /:status="nodeBusy"/)
  assert.match(assetPanelSource, /@retry="retryAssetFailedStep"/)
  assert.match(assetPanelSource, /function saveAsset\(\)/)
  assert.match(assetPanelSource, /await ctx\?\.refreshDrama\?\.\(true\)/)
  assert.match(assetPanelSource, /ctx\?\.nodeStatus\?\.success\(props\.nodeId, \{/)
  assert.match(assetPanelSource, /retryStep: 'save'/)
  assert.match(assetPanelSource, /素材库选图/)
  assert.match(assetPanelSource, /AssetPickerDialog/)
  assert.match(assetPanelSource, /关联分镜/)
  assert.match(assetPanelSource, /function highlightRelated\(\)/)
  assert.match(assetPanelSource, /function clearTransientAssetStatus\(\)/)
})

test('资产配置面板从项目素材库选图后写回画布资产绑定', () => {
  assert.match(assetPanelSource, /import \{ assetsAPI \} from '@\/api\/assets'/)
  assert.match(assetPanelSource, /async function bindPickedProjectAsset\(asset\)/)
  assert.match(assetPanelSource, /asset\?\.source_kind !== 'project'/)
  assert.match(assetPanelSource, /assetsAPI\.update\(asset\.raw_id/)
  assert.match(assetPanelSource, /canvas_asset_binding/)
  assert.match(assetPanelSource, /kind: props\.kind/)
  assert.match(assetPanelSource, /entity_id: props\.entity\.id/)
  assert.match(assetPanelSource, /node_id: props\.nodeId/)
  assert.match(assetPanelSource, /await bindPickedProjectAsset\(asset\)/)
  assert.match(assetPanelSource, /retryStep: 'library'/)
  assert.match(assetPanelSource, /libraryAsset: asset/)
  assert.match(assetPanelSource, /async function retryAssetFailedStep\(\)/)
  assert.match(assetPanelSource, /status\?\.retryStep === 'library' && status\.libraryAsset/)
})

test('媒体配置面板支持从素材库复用图片、视频和音频', () => {
  assert.match(mediaPanelSource, /从素材库选用图片/)
  assert.match(mediaPanelSource, /v-model="imageLibraryVisible"/)
  assert.match(mediaPanelSource, /type="image"/)
  assert.match(mediaPanelSource, /async function onLibraryImagePick\(asset\)/)
  assert.match(mediaPanelSource, /function imageAttachPayload\(imageUrl, localPath\)/)
  assert.match(mediaPanelSource, /last_frame_image_url: localPath \? null : imageUrl/)
  assert.match(mediaPanelSource, /last_frame_local_path: localPath \|\| null/)
  assert.match(mediaPanelSource, /first_frame_image_id: null/)
  assert.match(mediaPanelSource, /image_url: localPath \? null : imageUrl/)
  assert.match(mediaPanelSource, /local_path: localPath \|\| null/)
  assert.match(mediaPanelSource, /已将素材库图片设为本镜首帧/)
  assert.match(mediaPanelSource, /已将素材库图片设为本镜尾帧/)
  assert.match(mediaPanelSource, /已将素材库图片设为本镜分镜图/)
  assert.match(mediaPanelSource, /attachedSlot: imageAttachSlot\(\)/)
  assert.match(mediaPanelSource, /function libraryAttachSlot\(resultType\)/)
  assert.match(mediaPanelSource, /return imageAttachSlot\(\)/)
  assert.match(mediaPanelSource, /从素材库选用成片/)
  assert.match(mediaPanelSource, /from '@\/components\/AssetPickerDialog\.vue'/)
  assert.match(mediaPanelSource, /function libraryAssetUrl\(asset, resultType\)/)
  assert.match(mediaPanelSource, /asset\?\.image_url/)
  assert.match(mediaPanelSource, /asset\?\.asset_url \|\| asset\?\.display_url \|\| asset\?\.url/)
  assert.match(mediaPanelSource, /async function onLibraryAudioPick\(asset\)/)
  assert.match(mediaPanelSource, /从素材库选用音频/)
  assert.match(mediaPanelSource, /type="audio"/)
  assert.match(mediaPanelSource, /素材库音频挂载中/)
  assert.match(mediaPanelSource, /storyboardsAPI\.update\(sbId, \{/)
  assert.match(mediaPanelSource, /audio_local_path: localPath \|\| undefined/)
  assert.match(mediaPanelSource, /audio_url: localPath \? undefined : audioUrl/)
  assert.match(mediaPanelSource, /已将素材库音频设为该分镜音频/)
  assert.match(mediaPanelSource, /function libraryAssetLocalPath\(asset, resultType\)/)
  assert.match(mediaPanelSource, /asset\?\.image_local_path/)
  assert.match(mediaPanelSource, /asset\?\.audio_local_path \|\| asset\?\.voice_local_path/)
  assert.match(mediaPanelSource, /asset\?\.video_local_path/)
  assert.match(mediaPanelSource, /function libraryAssetStatusPayload\(asset, resultType\)/)
  assert.match(mediaPanelSource, /savedAssetId: asset\?\.raw_id \|\| asset\?\.id \|\| ''/)
  assert.match(mediaPanelSource, /\.\.\.libraryAssetStatusPayload\(asset, 'video'\)/)
  assert.match(mediaPanelSource, /\.\.\.libraryAssetStatusPayload\(asset, 'audio'\)/)
  assert.match(mediaPanelSource, /function markLibraryAttachFailure\(nodeId, resultType, asset, message\)/)
  assert.match(mediaPanelSource, /function libraryAttachRetryAction\(resultType\)/)
  assert.match(mediaPanelSource, /return 'attach_library_image'/)
  assert.match(mediaPanelSource, /function libraryAttachDefaultLabel\(resultType\)/)
  assert.match(mediaPanelSource, /libraryAsset: asset/)
  assert.match(mediaPanelSource, /retryAction === 'attach_library_image' && asset/)
  assert.match(mediaPanelSource, /await onLibraryImagePick\(asset\)/)
  assert.match(mediaPanelSource, /retryAction === 'attach_library_video' && asset/)
  assert.match(mediaPanelSource, /await onLibraryVideoPick\(asset\)/)
  assert.match(mediaPanelSource, /retryAction === 'attach_library_audio' && asset/)
  assert.match(mediaPanelSource, /await onLibraryAudioPick\(asset\)/)
  assert.match(dramaCanvasAdapterSource, /const dialogueAudio = sb\.audio_local_path \|\| sb\.audio_url/)
  assert.match(dramaCanvasAdapterSource, /url: audioUrl\(dialogueAudio\)/)
  assert.match(storyboardNodeSource, /props\.data\.storyboard\?\.audio_url/)
})

test('媒体配置面板失败后保留原因和重试入口', () => {
  assert.match(mediaPanelSource, /<CanvasNodeExecutionStrip/)
  assert.match(mediaPanelSource, /:status="activeNodeStatus"/)
  assert.match(mediaPanelSource, /@retry="retryFailedStep"/)
  assert.match(mediaPanelSource, /@continue="continueMediaNextStep"/)
  assert.match(mediaPanelSource, /const activeNodeStatus = computed/)
  assert.match(mediaPanelSource, /activeNodeStatus\.value\?\.step === 'failed'/)
  assert.match(mediaPanelSource, /retryStep: step/)
  assert.match(mediaPanelSource, /retryLabel/)
  assert.match(mediaPanelSource, /recoverable: true/)
  assert.match(mediaPanelSource, /async function retryFailedStep\(\)/)
  assert.match(mediaPanelSource, /await runStep\(step\)/)
  assert.match(mediaPanelSource, /async function continueMediaNextStep\(\)/)
})

test('分镜配置面板提供统一节点执行和失败恢复入口', () => {
  assert.match(nodeExecutionStripSource, /class="node-execution-strip"/)
  assert.match(nodeExecutionStripSource, /节点执行/)
  assert.match(nodeExecutionStripSource, /import \{ assetMediaUrl \} from '@\/utils\/mediaUrl'/)
  assert.match(nodeExecutionStripSource, /const resultUrl = computed\(\(\) => assetMediaUrl\(statusSavedAsset\.value\) \|\| props\.status\?\.savedAssetUrl \|\| props\.status\?\.resultUrl \|\| ''\)/)
  assert.match(nodeExecutionStripSource, /@click\.stop="openResult"/)
  assert.match(nodeExecutionStripSource, /@click\.stop="copyResult"/)
  assert.match(nodeExecutionStripSource, /@click\.stop="downloadResult"/)
  assert.match(nodeExecutionStripSource, /@click\.stop="copyStatusDetail"/)
  assert.match(nodeExecutionStripSource, /@click\.stop="copyPrompt"/)
  assert.match(nodeExecutionStripSource, /@click\.stop="copyRequestPayload"/)
  assert.match(nodeExecutionStripSource, /status\.step === 'failed' && status\.retryStep/)
  assert.match(nodeExecutionStripSource, /@click\.stop="\$emit\('retry'\)"/)
  assert.match(nodeExecutionStripSource, /status\.nextStep/)
  assert.match(nodeExecutionStripSource, /@click\.stop="\$emit\('continue'\)"/)
  assert.match(nodeExecutionStripSource, /status\.errorDetail \|\| status\.message \|\| status\.step/)
  assert.match(nodeExecutionStripSource, /navigator\.clipboard\?\.writeText/)
  assert.match(nodeExecutionStripSource, /ElMessageBox\.alert\(text, fallbackTitle/)
  assert.match(storyboardPanelSource, /<CanvasNodeExecutionStrip/)
  assert.match(storyboardPanelSource, /:status="activeNodeStatus"/)
  assert.match(storyboardPanelSource, /@retry="retryPanelFailedStep"/)
  assert.match(storyboardPanelSource, /@continue="continuePanelNextStep"/)
  assert.match(storyboardPanelSource, /const activeNodeStatus = computed/)
  assert.match(storyboardPanelSource, /function panelRuntimeNode\(\)/)
  assert.match(storyboardPanelSource, /type: 'canvasStoryboard'/)
  assert.match(storyboardPanelSource, /async function retryPanelFailedStep\(\)/)
  assert.match(storyboardPanelSource, /ctx\?\.nodeStatus\?\.clear\?\.\(sbNodeId\.value\)/)
  assert.match(storyboardPanelSource, /await ctx\?\.runNodeStep\?\.\(panelRuntimeNode\(\), step\)/)
  assert.match(storyboardPanelSource, /async function continuePanelNextStep\(\)/)
})

test('媒体配置面板成功后保留节点结果回显', () => {
  assert.match(mediaPanelSource, /function markNodeSuccess\(message, payload = \{\}\)/)
  assert.match(mediaPanelSource, /ctx\?\.nodeStatus\?\.success\(props\.nodeId, status\)/)
  assert.match(mediaPanelSource, /ctx\?\.nodeStatus\?\.success\(sbNodeId\.value, status\)/)
  assert.match(mediaPanelSource, /autoClear: payload\.autoClear \?\? false/)
  assert.match(mediaPanelSource, /resultType: 'video'/)
  assert.match(mediaPanelSource, /resultType: 'audio'/)
  assert.match(mediaPanelSource, /resultType: 'text'/)
  assert.match(mediaPanelSource, /promptText: nextText/)
  assert.match(mediaPanelSource, /promptText: universalText\.value\.trim\(\)/)
  assert.match(mediaPanelSource, /function clearRunningStatus\(nodeId\)/)
  assert.match(mediaPanelSource, /!\['failed', 'success'\]\.includes\(status\.step\)/)
  assert.match(mediaPanelSource, /function currentResultUrl\(step\)/)
})

test('节点运行结果浮层提供成功和失败后的闭环操作', () => {
  assert.match(nodeStatusOverlaySource, /<div v-if="hasResultPreview" class="result-preview"/)
  assert.match(nodeStatusOverlaySource, /节点生成结果预览/)
  assert.match(nodeStatusOverlaySource, /<video v-else-if="resultPreviewType === 'video'"/)
  assert.match(nodeStatusOverlaySource, /<audio v-else-if="resultPreviewType === 'audio'"/)
  assert.match(nodeStatusOverlaySource, /aria-label="结果操作"/)
  assert.match(nodeStatusOverlaySource, /@click\.stop="openResult"/)
  assert.match(nodeStatusOverlaySource, /@click\.stop="copyResultLink"/)
  assert.match(nodeStatusOverlaySource, /@click\.stop="downloadResult"/)
  assert.match(nodeStatusOverlaySource, /@click\.stop="saveResultAsset"/)
  assert.match(nodeStatusOverlaySource, /存入素材库/)
  assert.match(nodeStatusOverlaySource, /@click\.stop="attachImageResult\('main'\)"/)
  assert.match(nodeStatusOverlaySource, /@click\.stop="attachVideoResult"/)
  assert.match(nodeStatusOverlaySource, /@click\.stop="attachAudioResult"/)
  assert.match(nodeStatusOverlaySource, /aria-label="失败结果操作"/)
  assert.match(nodeStatusOverlaySource, /@click\.stop="copyError"/)
  assert.match(nodeStatusOverlaySource, /@click\.stop="retryFailed"/)
  assert.match(nodeStatusOverlaySource, /function markActionFailure\(message, retryActionName, retryActionLabel\)/)
  assert.match(nodeStatusOverlaySource, /retryAction: retryActionName/)
  assert.match(nodeStatusOverlaySource, /async function retryAction\(\)/)
})

test('项目素材节点聚焦后提供配置面板和挂载动作', () => {
  assert.match(projectAssetNodeSource, /v-if="data\.focused"/)
  assert.match(projectAssetNodeSource, /素材配置/)
  assert.match(projectAssetNodeSource, /import CanvasNodeExecutionStrip from '\.\/CanvasNodeExecutionStrip\.vue'/)
  assert.match(projectAssetNodeSource, /<CanvasNodeExecutionStrip/)
  assert.match(projectAssetNodeSource, /:status="activeNodeStatus"/)
  assert.match(projectAssetNodeSource, /@retry="retryFailedStep"/)
  assert.match(projectAssetNodeSource, /const activeNodeStatus = computed\(\(\) => ctx\?\.nodeStatus\?\.map\?\.\[props\.id\] \|\| null\)/)
  assert.match(projectAssetNodeSource, /async function retryFailedStep\(\)/)
  assert.match(projectAssetNodeSource, /closePanel/)
  assert.match(projectAssetNodeSource, /复制到提示词/)
  assert.match(projectAssetNodeSource, /指派到选中分镜/)
  assert.match(projectAssetNodeSource, /ctx\?\.runNodeStep\?\.\(\{ id: props\.id, type: 'canvasProjectAsset', data: props\.data \}, 'library'\)/)
  assert.match(projectAssetNodeSource, /ctx\?\.clearFocusedNode\?\.\(\)/)
})
