import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const canvasSource = readFileSync(resolve(__dirname, '../src/views/DramaCanvas.vue'), 'utf8')
const homeCanvasSource = readFileSync(resolve(__dirname, '../src/views/HomeCanvas.vue'), 'utf8')
const nodeSource = readFileSync(resolve(__dirname, '../src/components/dramaCanvas/HomeCanvasNode.vue'), 'utf8')
const contextMenuSource = readFileSync(resolve(__dirname, '../src/components/dramaCanvas/CanvasContextMenu.vue'), 'utf8')
const accountBadgeSource = readFileSync(resolve(__dirname, '../src/components/AccountBadge.vue'), 'utf8')
const imagesSource = readFileSync(resolve(__dirname, '../src/api/images.js'), 'utf8')
const videosSource = readFileSync(resolve(__dirname, '../src/api/videos.js'), 'utf8')
const generationSource = readFileSync(resolve(__dirname, '../src/utils/freeCanvasGeneration.js'), 'utf8')

test('自由节点配置面板保存并回填模型、比例和时长字段，并记住视频参数', () => {
  assert.match(canvasSource, /freeNodeForm = ref\(\{ title: '', content: '', url: '', model: '', aspectRatio: '16:9', duration: 5 \}\)/)
  assert.match(canvasSource, /<el-form-item label="模型">/)
  assert.match(canvasSource, /v-model="freeNodeForm\.model"/)
  assert.match(canvasSource, /v-if="\['image', 'video'\]\.includes\(freeNodeKind\)" label="画面比例"/)
  assert.match(canvasSource, /v-if="freeNodeKind === 'video'" label="视频时长/)
  assert.match(canvasSource, /model: node\?\.data\?\.model \|\| kindDefaults\.model \|\| ''/)
  assert.match(canvasSource, /aspectRatio: node\?\.data\?\.aspectRatio \|\| kindDefaults\.aspectRatio \|\| '16:9'/)
  assert.match(canvasSource, /duration: node\?\.data\?\.duration \|\| kindDefaults\.duration \|\| 5/)
  assert.match(canvasSource, /request\.get\('\/canvas\/model-catalog'\)/)
  assert.match(canvasSource, /canvasModelOptions\(freeCanvasModelCatalog\.value, kind, \{ referenceCount \}\)/)
  assert.doesNotMatch(canvasSource, /aiAPI\.list\(/)
  assert.match(canvasSource, /function getFreeNodeModelOptions\(kind, nodeOrId\) \{[\s\S]{0,220}getFreeNodeModelOptionEntriesForNode\(kind, nodeOrId\)/)
  assert.match(canvasSource, /v-for="option in getFreeNodeModelOptionEntriesForNode\(freeNodeKind, freeNodeEditingId\)"[\s\S]{0,180}:key="option\.value"[\s\S]{0,180}:value="option\.value"/)
  assert.doesNotMatch(canvasSource, /getSelectableModelsAcrossConfigs\(freeCanvasModelConfigs\.value, serviceType\)/)
  assert.doesNotMatch(canvasSource, /allow-create/)
  assert.match(canvasSource, /FREE_CANVAS_DEFAULTS_STORAGE_KEY/)
  assert.match(canvasSource, /function loadFreeCanvasNodeDefaults\(\)/)
  assert.match(canvasSource, /function persistFreeCanvasNodeDefaults\(kind, data\)/)
  assert.match(canvasSource, /const defaults = loadFreeCanvasNodeDefaults\(\)/)
  assert.match(nodeSource, /ctx\?\.getFreeNodeModelOptions\?\.\(props\.data\.kind, props\.id\)/)
  assert.match(nodeSource, /<select[\s\S]*v-model="draft\.model"[\s\S]*aria-label="生成模型"/)
  assert.match(nodeSource, /<option v-for="option in modelOptions" :key="option\.value" :value="option\.value" :disabled="option\.disabled">\{\{ option\.label \}\}<\/option>/)
  assert.doesNotMatch(nodeSource, /<datalist v-if="modelOptions\.length"/)
})

test('首页与项目画布向节点提供带 value 和 label 的模型选项', () => {
  assert.match(homeCanvasSource, /canvasModelOptions,/)
  assert.match(homeCanvasSource, /function getFreeNodeModelOptions\(kind\) \{\s*return canvasModelOptions\(homeCanvasModelCatalog\.value, kind\)\s*\}/)
  assert.match(canvasSource, /function getFreeNodeModelOptions\(kind, nodeOrId\) \{\s*return getFreeNodeModelOptionEntriesForNode\(kind, nodeOrId\)\s*\}/)
  assert.doesNotMatch(canvasSource, /getFreeNodeModelOptionEntriesForNode\(kind, nodeOrId\)\.map\(\(item\) => item\.value\)/)
})

test('每种自由生成节点在底部醒目显示随参数变化的本次积分', () => {
  assert.match(nodeSource, /v-if="canGenerate" class="billing-cost canvas-credit-callout-v1" aria-live="polite"/)
  assert.match(nodeSource, /本次预计扣除/)
  assert.match(nodeSource, /<strong>\{\{ estimatedCredits \}\}<\/strong>/)
  assert.match(nodeSource, /积分待管理员配置/)
  assert.match(nodeSource, /getFreeNodeEstimatedCredits\?\.\([\s\S]*draft\.quantity,[\s\S]*draft\.duration/)
  assert.doesNotMatch(nodeSource, /class="billing-note">\{\{ estimatedCredits/)
  assert.match(nodeSource, /\.billing-cost\s*\{[\s\S]*border:\s*1px solid rgba\(255, 177, 92, 0\.65\)/)
  assert.match(nodeSource, /\.billing-cost\s*\{[\s\S]*background:\s*rgba\(124, 64, 20, 0\.42\)/)
  assert.match(nodeSource, /\.billing-cost\s*\{[\s\S]*font-weight:\s*800/)
  assert.match(nodeSource, /\.billing-cost strong\s*\{[\s\S]*color:\s*#ffb15c[\s\S]*font-size:\s*18px[\s\S]*font-weight:\s*900/)
  assert.match(nodeSource, /<option v-for="option in modelOptions"[\s\S]{0,160}:value="option\.value"[\s\S]{0,160}\{\{ option\.label \}\}/)
})

test('HomeCanvasNode 提供状态显示和配置生成入口，并通过画布上下文调用父级', () => {
  assert.match(nodeSource, /useCanvasContext/)
  assert.match(nodeSource, /ctx\?\.openFreeNodeConfig\?\.\(props\.id\)/)
  assert.match(nodeSource, /ctx\?\.runFreeCanvasNode\?\.\(props\.id\)/)
  assert.match(nodeSource, /ctx\?\.retryFreeCanvasAssetSave\?\.\(props\.id\)/)
  assert.match(nodeSource, /assetSaveFailed = computed\(\(\) => props\.data\.status === 'success'[\s\S]*props\.data\.assetSaveStatus === 'failed'[\s\S]*Boolean\(primaryResultUrl\.value\)/)
  assert.match(nodeSource, /v-if="assetSaveFailed"[\s\S]*重试入库/)
  assert.match(nodeSource, /node-status/)
  assert.match(nodeSource, /data\.status === 'running'/)
  assert.match(nodeSource, /data\.status === 'failed'/)
  assert.match(nodeSource, /@click\.stop="openConfig"/)
  assert.match(nodeSource, /@click\.stop="runNode"/)
})

test('选中自由节点展开专属编辑器，视频节点可见展示自动采用的媒体连线', () => {
  assert.match(nodeSource, /v-if="isSelected && !hasMultiSelection && !editorHidden"[\s\S]*class="node-expanded-editor canvas-node-panel nodrag nopan"/)
  assert.match(nodeSource, /:aria-label="editorLabel"/)
  assert.match(nodeSource, /:aria-label="data\.kind === 'video' \? '自动参考素材' : '自动参考图'"/)
  assert.match(nodeSource, /ctx\?\.getFreeNodeInputReferences\?\.\(props\.id\)/)
  assert.match(nodeSource, /reference\.ready \? 'ready' : 'pending'/)
  assert.match(nodeSource, /把图片、视频或音频节点连接到视频节点；首尾帧、多图参考和全能参考会按当前模式真实提交/)
  assert.match(nodeSource, /<img v-if="referencePreviewUrl\(reference\) && reference\.kind === 'image'"/)
  assert.match(nodeSource, /loadProtectedMediaPreview\(url\)/)
  assert.match(nodeSource, /<span v-else class="reference-placeholder">/)
  assert.match(canvasSource, /getFreeNodeInputReferences: freeCanvasNodeInputReferences/)
  assert.match(canvasSource, /视频节点已采用该\$\{mediaLabel\}作为参考素材/)
})

test('视频节点首尾帧模式写回节点并持续映射后续参考图', () => {
  assert.match(nodeSource, /@click="setVideoReferenceMode\('first-last'\)"/)
  assert.match(nodeSource, /draft\.videoReferenceMode = normalizeFreeCanvasVideoReferenceMode\(mode\)/)
  assert.match(nodeSource, /videoReferenceMode: videoReferenceMode\.value/)
  assert.match(nodeSource, /watch\([\s\S]*inputReferences\.value\.map[\s\S]*let imageIndex = 0[\s\S]*reference\.kind === 'image'[\s\S]*const index = isImage \? imageIndex\+\+ : -1[\s\S]*resolveFreeCanvasVideoReferenceInput\(videoReferenceMode\.value, index\)/)
  assert.match(nodeSource, /reference\.enabled !== enabled[\s\S]*updateReference\(reference, patch\)/)
})

test('图片编辑器上传参考图，视频编辑器上传图片、视频或音频且 @ 只列出直连图片', () => {
  assert.match(nodeSource, /v-if="canUploadReference" type="button" :aria-label="data\.kind === 'video' \? '上传参考素材' : '上传参考图'"/)
  assert.match(nodeSource, /v-if="canUploadReference"\s+ref="referenceFileInput"/)
  assert.match(nodeSource, /ctx\?\.uploadFreeCanvasReferenceMedia\?\.\(props\.id, file\)/)
  assert.match(nodeSource, /@input="handleEditorInput"/)
  assert.match(nodeSource, /function handleEditorInput\(event\) \{[\s\S]*handlePromptInput\(event\)[\s\S]*scheduleDraftSave\(\)/)
  assert.match(nodeSource, /v-if="showReferenceMention"[\s\S]*aria-label="@选择参考图"/)
  assert.match(nodeSource, /@mousedown\.prevent="selectReferenceMention\(candidate\)"/)
  assert.match(nodeSource, /const mentionToken = String\(candidate\?\.mentionToken \|\| ''\)[\s\S]*draft\.content = `\$\{draft\.content\.slice\(0, mentionStart\.value\)\}\$\{mentionToken\} \$\{draft\.content\.slice\(mentionEnd\.value\)\}`/)
  assert.match(nodeSource, /canvas-reference-numbered-mentions-v1/)
  assert.match(nodeSource, /<span>\{\{ candidate\.label \}\}<\/span>/)
  assert.match(nodeSource, /candidate\?\.mentionToken/)
  assert.doesNotMatch(nodeSource, /@\$\{candidate\.title\}/)
  assert.match(nodeSource, /ctx\?\.attachFreeCanvasReference\?\.\(props\.id, sourceNodeId\)/)
  assert.doesNotMatch(nodeSource, /<select[\s\S]{0,160}aria-label="@选择参考图"/)
  assert.match(canvasSource, /async function uploadFreeCanvasReferenceMedia\(nodeOrId, file\)/)
  assert.match(canvasSource, /await createFreeCanvasReferenceNode\(\{[\s\S]*targetNode,[\s\S]*url,/)
  assert.match(canvasSource, /function attachFreeCanvasReference\(targetNodeOrId, sourceNodeOrId\)/)
  assert.match(canvasSource, /onConnect\(\{ source: sourceNode\.id, target: targetNode\.id \}\)/)
  assert.match(canvasSource, /uploadFreeCanvasReferenceMedia,\s*\n\s*attachFreeCanvasReference,/)
  assert.match(canvasSource, /function freeCanvasReferenceCandidates\(nodeOrId\)[\s\S]{0,700}planFreeCanvasVideoReferences[\s\S]{0,700}return buildFreeCanvasReferenceMentionCandidates\(\s*adoptedReferences\([\s\S]{0,300}collectDirectUpstreamImageReferences/)
  assert.doesNotMatch(canvasSource, /function freeCanvasReferenceCandidates[\s\S]{0,500}allGraphNodes\.value\s*\.filter/)
  assert.match(homeCanvasSource, /function freeCanvasReferenceCandidates\(nodeOrId\)[\s\S]{0,500}buildFreeCanvasReferenceMentionCandidates\([\s\S]*collectDirectUpstreamImageReferences/)
  assert.doesNotMatch(homeCanvasSource, /function freeCanvasReferenceCandidates[\s\S]{0,600}!connectedNodeIds\.has/)
})

test('图片和视频节点都允许通过 @ 选择直连图片参考，其他节点不启用', () => {
  assert.match(nodeSource, /const supportsReferenceMention = computed\(\(\) => \['image', 'video'\]\.includes\(props\.data\.kind\)\)/)
  assert.match(nodeSource, /const referenceCandidates = computed\(\(\) => \(\s*supportsReferenceMention\.value/)
  assert.match(nodeSource, /function handlePromptInput\(event\) \{\s*if \(!supportsReferenceMention\.value\) return/)
  assert.match(nodeSource, /const showReferenceMention = computed\(\(\) => supportsReferenceMention\.value && mentionStart\.value >= 0\)/)
})

test('自由节点可从节点内和右键挂载兼容素材，并拒绝修改不兼容节点', () => {
  assert.match(nodeSource, /ctx\?\.openFreeNodeAssetLibrary\?\.\(props\.id\)/)
  assert.match(nodeSource, /v-if="canMountAsset"[\s\S]*素材库/)
  assert.match(contextMenuSource, /type: 'mount-free-node-asset'[\s\S]*label: '挂载素材'/)
  assert.match(canvasSource, /const canvasAssetPickerTargetFreeNodeId = ref\(''\)/)
  assert.match(canvasSource, /function openFreeNodeAssetLibrary\(nodeOrId\)/)
  assert.match(canvasSource, /canvasAssetPickerTargetFreeNodeId\.value = String\(node\.id\)/)
  assert.match(canvasSource, /if \(assetType !== targetNode\.data\?\.kind\)/)
  assert.match(canvasSource, /await patchFreeCanvasNodeData\(targetFreeNodeId, \{[\s\S]*url,[\s\S]*savedAssetId: String\(projectAssetId\(projectAsset\) \|\| ''\),[\s\S]*assetSaveStatus: 'success'[\s\S]*imageToolStatus: ''[\s\S]*imageToolError: ''/)
  assert.match(canvasSource, /if \(targetFreeNodeId\) \{[\s\S]*ElMessage\.error\(e\?\.message \|\| '素材挂载失败'\)[\s\S]*return/)
})

test('自由节点右键支持复制和删除，复制节点清除运行任务并偏移落点', () => {
  assert.match(contextMenuSource, /type: 'duplicate-free-node'[\s\S]*label: '创建副本'/)
  assert.match(contextMenuSource, /type: 'delete-free-node'[\s\S]*label: '删除节点'/)
  assert.match(canvasSource, /cloneSingleCanvasNodeWithIncidentEdges/)
  assert.match(canvasSource, /async function duplicateFreeCanvasNode\(nodeOrId\)/)
  assert.match(canvasSource, /x: Number\(source\.position\?\.x \|\| 0\) \+ 40/)
  assert.match(canvasSource, /y: Number\(source\.position\?\.y \|\| 0\) \+ 40/)
  assert.match(canvasSource, /taskId: ''/)
  assert.match(canvasSource, /allGraphEdges\.value = decorateCanvasEdges\(\[\s*\.\.\.allGraphEdges\.value\.map\(\(edge\) => \(\{ \.\.\.edge, selected: false \}\)\),\s*\.\.\.clonedEdges,\s*\]\)/)
  assert.match(canvasSource, /type === 'duplicate-free-node'[\s\S]*await duplicateFreeCanvasNode\(node\)/)
  assert.match(canvasSource, /type === 'delete-free-node'[\s\S]*await deleteFreeCanvasNode\(node\.id\)/)
})

test('项目独立画布撤销重做恢复自由节点和副本连线同一快照', () => {
  assert.match(canvasSource, /restoreCanvasInteractionFreeNodes/)
  assert.match(canvasSource, /allGraphNodes\.value = restoreCanvasInteractionFreeNodes\(/)
  assert.match(canvasSource, /allGraphEdges\.value = decorateCanvasEdges\(state\?\.edges \|\| allGraphEdges\.value\)/)
})

test('独立画布支持 WASD 平移和宽容连线', () => {
  assert.match(canvasSource, /v-bind="canvasConnectionInteractionOptions"/)
  assert.match(canvasSource, /CANVAS_KEYBOARD_PAN_INITIAL_STEP,[\s\S]*from '@\/utils\/canvasKeyboardPan'/)
  assert.match(canvasSource, /function panCanvasByKeyboard\(key\)/)
  assert.match(canvasSource, /\['w', 'a', 's', 'd'\]\.includes\(key\)/)
  assert.match(canvasSource, /vector\.x \* CANVAS_KEYBOARD_PAN_INITIAL_STEP/)
  assert.match(canvasSource, /canvasFlowApi\.value\?\.setViewport\?\.\(nextViewport, \{ duration: 0 \}\)/)
})

test('自由节点保留最近生成历史并可从右键查看', () => {
  assert.match(canvasSource, /const FREE_CANVAS_GENERATION_HISTORY_LIMIT = 20/)
  assert.match(canvasSource, /async function appendFreeCanvasGenerationHistory\(nodeId, entry\)/)
  assert.match(canvasSource, /async function updateFreeCanvasGenerationHistory\(nodeId, historyId, patch\)/)
  assert.match(canvasSource, /historyId = `run:/)
  assert.match(canvasSource, /status: 'running'/)
  assert.match(canvasSource, /status: 'success'/)
  assert.match(canvasSource, /status: 'failed'/)
  assert.match(canvasSource, /view-generation-history/)
  assert.match(contextMenuSource, /type: 'view-generation-history'[\s\S]*label: '生成历史'/)
})

test('独立画布自由节点走真实生成分支，禁止污染剧集 runCanvasNodeStep', () => {
  assert.match(canvasSource, /import request from '@\/utils\/request'/)
  assert.match(canvasSource, /collectDirectUpstreamImageReferences/)
  assert.match(canvasSource, /canvasModelRoute/)
  assert.match(canvasSource, /buildFreeCanvasGenerationRequest/)
  assert.match(canvasSource, /buildFreeCanvasProjectAssetPayload/)
  assert.match(canvasSource, /resolveFreeCanvasResultUrl/)
  assert.match(canvasSource, /async function runFreeCanvasNode\(nodeOrId\)/)
  assert.match(canvasSource, /if \(!isStandaloneCanvas\.value \|\| node\?\.type !== 'homeCanvasNode'\)/)
  assert.match(canvasSource, /const upstreamReferences = freeCanvasNodeInputReferences\(node\)[\s\S]*const upstreamUrls = upstreamReferences[\s\S]*const generationData = \{ \.\.\.node\.data, model: catalogEntry\.model \}[\s\S]*requestPayload = buildFreeCanvasGenerationRequest\(generationData, \{[\s\S]*dramaId: dramaId\.value,[\s\S]*upstreamUrls,[\s\S]*upstreamReferences/)
  assert.match(canvasSource, /const modelRoute = canvasModelRoute\(freeCanvasModelCatalog\.value, kind, node\.data\?\.model\)/)
  assert.match(canvasSource, /\.\.\.\(kind === 'image' \? \{ configId: modelRoute\?\.configId \} : \{\}\)/)
  assert.match(canvasSource, /if \(kind === 'image'\) submitResult = await imagesAPI\.create\(requestPayload\)/)
  assert.match(canvasSource, /else if \(kind === 'video'\) submitResult = await videosAPI\.create\(requestPayload\)/)
  assert.match(canvasSource, /else if \(kind === 'audio'\) submitResult = await request\.post\('\/audio\/extract', requestPayload\)/)
  assert.match(canvasSource, /buildFreeCanvasGenerationRequest\(generationData/)
  assert.match(canvasSource, /async function runCanvasNodeStep\(node, step\) \{[\s\S]*if \(isStandaloneCanvas\.value && node\?\.type === 'homeCanvasNode'\)/)
})

test('自由节点运行结果可轮询、失败写回、成功自动入库并保留旧 url', () => {
  assert.match(canvasSource, /async function pollFreeCanvasTask\(taskId/)
  assert.match(canvasSource, /pollFreeCanvasTaskStatus\(taskId, \{ \.\.\.options, getTask: taskAPI\.get \}\)/)
  assert.match(canvasSource, /FREE_CANVAS_TASK_NEEDS_ATTENTION/)
  assert.match(generationSource, /if \(task\?\.status === 'completed'\) return task/)
  assert.match(generationSource, /FREE_CANVAS_TASK_STATUS_UNAVAILABLE/)
  assert.match(generationSource, /FREE_CANVAS_TASK_RESULT_PENDING/)
  assert.match(canvasSource, /patchFreeCanvasNodeData\(node\.id, \{\s*model: requestPayload\.model \|\| node\.data\?\.model \|\| '',\s*status: 'running'/)
  assert.match(canvasSource, /patchFreeCanvasNodeData\(node\.id, \{[\s\S]*status: 'running'[\s\S]*error: ''/)
  assert.match(canvasSource, /patchFreeCanvasNodeData\(node\.id, \{[\s\S]*status: 'success'[\s\S]*url: resultUrl[\s\S]*assetSaveStatus: 'running'[\s\S]*assetSaveError: ''/)
  assert.match(canvasSource, /patchFreeCanvasNodeData\(node\.id, \{[\s\S]*status: 'failed'[\s\S]*error: errorMessage/)
  assert.match(canvasSource, /const completedResults = \[\]/)
  assert.match(canvasSource, /const completedResultUrls = completedResults\.map/)
  assert.match(canvasSource, /const visibleResult = completedResults\[0\]/)
  assert.match(canvasSource, /resultUrl: visibleResult\.resultUrl/)
  assert.match(canvasSource, /resultUrls: completedResultUrls/)
  assert.match(canvasSource, /status: 'failed'[\s\S]*url: previousUrl[\s\S]*resultUrls: previousResultUrls/)
  assert.match(canvasSource, /buildFreeCanvasProjectAssetPayload\(\{[\s\S]*storyboard_id: null/)
  assert.match(canvasSource, /patchFreeCanvasNodeData\(nodeId, \{ assetSaveStatus: 'running', assetSaveError: '' \}/)
  assert.match(canvasSource, /await assetsAPI\.create\(assetPayload\)/)
  assert.match(canvasSource, /assetSaveStatus: 'success'[\s\S]*assetSaveError: ''[\s\S]*savedAssetId: String\(savedAsset\?\.id \|\| ''\)/)
  assert.match(canvasSource, /assetSaveStatus: 'failed'[\s\S]*assetSaveError: error\?\.message \|\| '自动存入素材库失败'/)
  assert.match(canvasSource, /async function retryFreeCanvasAssetSave\(nodeOrId\)/)
  assert.match(canvasSource, /retryFreeCanvasAssetSave,\s*\r?\n/)
  assert.match(canvasSource, /save-node-result-asset[\s\S]*saveFreeCanvasResultAsset\(node, node\.data\?\.kind, nodeResultUrl\(node\), null, node\.data\?\.taskId \|\| ''\)[\s\S]*ElMessage\.error\(error\?\.message \|\| '存入素材库失败'\)/)
  assert.match(canvasSource, /function resumePendingFreeCanvasTasks\(\)[\s\S]*node\?\.data\?\.status !== 'running'[\s\S]*void resumeFreeCanvasNodeTask\(node\)/)
  assert.match(canvasSource, /async function resumeFreeCanvasNodeTask\(nodeOrId\)[\s\S]*await pollFreeCanvasTask\(taskId,[\s\S]*isFreeCanvasTaskStillPending\(error\)[\s\S]*status: 'running'[\s\S]*generationActive: false[\s\S]*status: 'failed'/)
  assert.match(canvasSource, /await loadForDrama\(drama\.value, filterEpisodeId\.value\)[\s\S]*rebuildGraph\(\)[\s\S]*resumePendingFreeCanvasTasks\(\)/)
})

test('画布保存只使用容灾协调器并由状态机统一提示', () => {
  const unmountSource = canvasSource.slice(canvasSource.indexOf('onBeforeUnmount('))

  assert.doesNotMatch(canvasSource, /canvasPersistQueue/)
  assert.match(canvasSource, /dramaAPI\.saveCanvasLayout\([\s\S]{0,500}\{ silentError: true \}[\s\S]{0,80}\)/)
  assert.match(canvasSource, /layoutPersistence\.update\([\s\S]{0,500}\{ allowRetry: layoutOnly && groupsPayload === undefined \}\s*\)/)
  assert.match(canvasSource, /import\s*\{[^}]*onBeforeRouteLeave[^}]*\}\s*from\s*['"]vue-router['"]/s)
  assert.match(canvasSource, /async function flushPendingLayoutSave\(\) \{[\s\S]{0,500}clearTimeout\(saveTimer\)[\s\S]{0,200}saveTimer = null[\s\S]{0,300}await persistCanvasState\(\{ layoutOnly: true \}\)[\s\S]{0,300}layoutPersistence\.dirty[\s\S]{0,150}await layoutPersistence\.flushNow\(\)[\s\S]{0,200}return !layoutPersistence\.dirty/)
  assert.match(canvasSource, /onBeforeRouteLeave\(async \(\) => \{\s*if \(!await flushPendingLayoutSave\(\)\) return false\s*\}\)/)
  assert.match(unmountSource, /^onBeforeUnmount\(\(\) => \{[\s\S]*clearTimeout\(saveTimer\)[\s\S]*layoutPersistence\.dispose\(\)/)
  assert.doesNotMatch(unmountSource, /persistCanvasState|layoutPersistence\.flush/)
  assert.match(canvasSource, /layoutSaveState\.value = event\.state/)
  assert.match(canvasSource, /event\.state === 'retry_wait'[\s\S]{0,500}网络暂时不可用，画布将在后台自动重试保存/)
  assert.match(canvasSource, /画布已恢复并保存/)
  assert.match(canvasSource, /\['saving', 'retry_wait'\]\.includes\(layoutSaveState\.value\)/)
  assert.match(canvasSource, /async function removeNodeFromWorkflowGroup\(node\) \{\s*if \(workflowRunning\.value \|\| layoutSaveBusy\.value\) \{\s*ElMessage\.warning\('请等待当前画布保存或任务完成后再移出工作流'\)\s*return\s*\}[\s\S]{0,900}workflowGroups\.value = nextGroups/)
  assert.match(canvasSource, /async function onCreateWorkflowGroup\(\) \{[\s\S]{0,800}await ElMessageBox\.prompt\([\s\S]{0,400}\)\s*if \(workflowRunning\.value \|\| layoutSaveBusy\.value\) \{\s*ElMessage\.warning\('请等待当前画布任务完成后再创建工作流'\)\s*return\s*\}[\s\S]{0,250}workflowGroups\.value = createWorkflowGroup/)
  assert.match(canvasSource, /async function onDeleteActiveGroup\(\) \{\s*if \(workflowRunning\.value \|\| layoutSaveBusy\.value\) \{\s*ElMessage\.warning\('请等待当前画布任务完成后再删除工作流'\)\s*return\s*\}[\s\S]{0,500}await ElMessageBox\.confirm\([\s\S]{0,250}\)\s*if \(workflowRunning\.value \|\| layoutSaveBusy\.value\) \{\s*ElMessage\.warning\('请等待当前画布任务完成后再删除工作流'\)\s*return\s*\}[\s\S]{0,250}workflowGroups\.value = deleteWorkflowGroup/)
})

test('更新自由节点参考素材后使用现有持久化队列保存，不调用不存在的 scheduleSave', () => {
  assert.match(canvasSource, /function updateFreeCanvasReference\(edgeId, patch = \{\}\)[\s\S]*void persistCanvasState\(\{ layoutOnly: true \}\)/)
  assert.doesNotMatch(canvasSource, /\bscheduleSave\s*\(/)
})

test('自由节点素材入库使用 single-flight 并在 create 前检查已入库状态', () => {
  assert.match(canvasSource, /const freeCanvasAssetSaveFlights = new Map\(\)/)
  assert.match(canvasSource, /const saveKey = `\$\{nodeId\}::\$\{url\}`/)
  assert.match(canvasSource, /const existingFlight = freeCanvasAssetSaveFlights\.get\(saveKey\)[\s\S]*if \(existingFlight\) return existingFlight/)
  assert.match(canvasSource, /const savePromise = \(async \(\) => \{[\s\S]*const latestBeforeRun = freeCanvasNodeById\(nodeId\) \|\| node[\s\S]*if \(latestBeforeRun\?\.data\?\.savedAssetId\)[\s\S]*return \{ id: latestBeforeRun\.data\.savedAssetId, skipped: true \}/)
  assert.match(canvasSource, /const latestBeforeCreate = freeCanvasNodeById\(nodeId\) \|\| latestBeforeRun[\s\S]*if \(latestBeforeCreate\?\.data\?\.savedAssetId\)[\s\S]*return \{ id: latestBeforeCreate\.data\.savedAssetId, skipped: true \}[\s\S]*await assetsAPI\.create\(assetPayload\)/)
  assert.match(canvasSource, /freeCanvasAssetSaveFlights\.set\(saveKey, savePromise\)[\s\S]*finally \{[\s\S]*freeCanvasAssetSaveFlights\.delete\(saveKey\)/)
})

test('图片和视频 API 提供 get 回读包装', () => {
  assert.match(imagesSource, /get\(id\) \{[\s\S]*return request\.get\(`\/images\/\$\{id\}`\)/)
  assert.match(videosSource, /get\(id\) \{[\s\S]*return request\.get\(`\/videos\/\$\{id\}`\)/)
})

test('视频完成后回写成片首尾帧，并在结算后刷新积分余额', () => {
  assert.match(canvasSource, /async function resolveFreeCanvasVideoBoundaryFrames\(/)
  assert.match(canvasSource, /outputFirstFrameUrl/)
  assert.match(canvasSource, /outputLastFrameUrl/)
  assert.match(canvasSource, /moli:credit-account-refresh/)
  assert.match(accountBadgeSource, /moli:credit-account-refresh/)
})

test('画布分享打开真实工作区协作成员入口', () => {
  assert.match(canvasSource, /listTenantMembers/)
  assert.match(canvasSource, /addTenantMember/)
  assert.match(canvasSource, /画布协作/)
})
